#!/usr/bin/env bash
# Per-branch isolated PostgreSQL container for integration tests.
# Usage: bash scripts/make/test-db.sh {up|down|status}
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
IMAGE="analysi-postgres:15-partman"
CONTAINER_PREFIX="analysi-testpg"
PORT_RANGE_START=54320
PORT_RANGE_SIZE=80
DB_USER="testuser"
DB_PASSWORD="testpass"
ENV_LOCAL_FILE="${REPO_ROOT}/.env.test.local"

# ── Helpers ──────────────────────────────────────────────────────────────────

branch_slug() {
    local branch
    branch=$(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || true)
    if [ -z "$branch" ] || [ "$branch" = "HEAD" ]; then
        branch=$(git -C "$REPO_ROOT" rev-parse --short=8 HEAD 2>/dev/null || echo "unknown")
    fi
    # Sanitize: lowercase, replace non-alnum with underscore, collapse, truncate
    echo "$branch" \
        | tr '[:upper:]' '[:lower:]' \
        | sed 's/[^a-z0-9]/_/g' \
        | sed 's/__*/_/g' \
        | sed 's/^_//;s/_$//' \
        | cut -c1-40
}

testdb_port() {
    local slug="$1"
    local hash
    hash=$(printf '%s' "$slug" | cksum | awk '{print $1}')
    echo $(( PORT_RANGE_START + (hash % PORT_RANGE_SIZE) ))
}

container_name() {
    echo "${CONTAINER_PREFIX}-${1}"
}

db_name() {
    echo "analysi_test_${1}"
}

wait_for_ready() {
    local container="$1"
    local timeout=30
    local elapsed=0
    echo "Waiting for PostgreSQL to be ready..."
    while ! docker exec "$container" pg_isready -U "$DB_USER" -q 2>/dev/null; do
        sleep 1
        elapsed=$((elapsed + 1))
        if [ "$elapsed" -ge "$timeout" ]; then
            echo "ERROR: PostgreSQL did not become ready within ${timeout}s"
            docker logs "$container" --tail 20
            exit 1
        fi
    done
}

_write_env_local() {
    local slug="$1" container="$2" port="$3" dbname="$4"
    cat > "$ENV_LOCAL_FILE" <<EOF
# Auto-generated by 'make test-db-up' — do not edit manually.
# Branch: $(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "$slug")
# Container: ${container}
TEST_DB_HOST=localhost
TEST_DB_PORT=${port}
TEST_DB_USER=${DB_USER}
TEST_DB_PASSWORD=${DB_PASSWORD}
TEST_DB_NAME=${dbname}
DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@localhost:${port}/${dbname}
EOF
}

ensure_image() {
    if ! docker image inspect "$IMAGE" >/dev/null 2>&1; then
        echo "Building $IMAGE (first time)..."
        docker build -t "$IMAGE" "${REPO_ROOT}/deployments/docker/postgres/"
    fi
}

# ── Commands ─────────────────────────────────────────────────────────────────

cmd_up() {
    local slug port container dbname

    slug=$(branch_slug)
    port=$(testdb_port "$slug")
    container=$(container_name "$slug")
    dbname=$(db_name "$slug")

    # Already running?
    if docker ps --format '{{.Names}}' | grep -q "^${container}$"; then
        echo "Test DB already running: ${container} (port ${port})"
        echo "Database: ${dbname}"
        # Ensure .env.test.local exists (may be missing if previous run failed mid-setup)
        if [ ! -f "$ENV_LOCAL_FILE" ]; then
            _write_env_local "$slug" "$container" "$port" "$dbname"
            echo "Wrote missing ${ENV_LOCAL_FILE}"
        else
            echo "Config:   ${ENV_LOCAL_FILE}"
        fi
        return 0
    fi

    # Remove stopped container with same name (leftover from previous run)
    docker rm -f "$container" 2>/dev/null || true

    ensure_image

    echo "Starting test DB for branch '$(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "$slug")'..."
    echo "  Container: ${container}"
    echo "  Port:      ${port}"
    echo "  Database:  ${dbname}"

    # Start the container
    if ! docker run -d \
        --name "$container" \
        -v "${container}-data:/var/lib/postgresql/data" \
        -e POSTGRES_USER="$DB_USER" \
        -e POSTGRES_PASSWORD="$DB_PASSWORD" \
        -e POSTGRES_DB="$dbname" \
        -e POSTGRES_HOST_AUTH_METHOD=md5 \
        -p "${port}:5432" \
        "$IMAGE" \
        postgres \
            -c fsync=off \
            -c full_page_writes=off \
            -c synchronous_commit=off \
            -c "shared_preload_libraries=pg_partman_bgw" \
            -c max_locks_per_transaction=256 \
            -c shared_buffers=32MB \
            -c work_mem=2MB \
        2>&1; then
        echo ""
        echo "ERROR: Failed to start container. Port ${port} may be in use."
        echo "Try:  TEST_DB_PORT=<free_port> make test-db-up"
        exit 1
    fi

    wait_for_ready "$container"

    # Enable extensions (-h localhost forces TCP; Unix socket may not be ready)
    echo "Enabling extensions..."
    docker exec "$container" psql -h localhost -U "$DB_USER" -d "$dbname" -q -c \
        "CREATE EXTENSION IF NOT EXISTS pgcrypto;"
    docker exec "$container" psql -h localhost -U "$DB_USER" -d "$dbname" -q -c \
        "CREATE SCHEMA IF NOT EXISTS partman;"
    docker exec "$container" psql -h localhost -U "$DB_USER" -d "$dbname" -q -c \
        "CREATE EXTENSION IF NOT EXISTS pg_partman SCHEMA partman;"
    docker exec "$container" psql -h localhost -U "$DB_USER" -d "$dbname" -q -c \
        "CREATE EXTENSION IF NOT EXISTS vector;" 2>/dev/null || true

    # Run Flyway migrations (share the container's network namespace)
    echo "Running Flyway migrations..."
    docker run --rm \
        --network="container:${container}" \
        -v "${REPO_ROOT}/migrations/flyway/sql:/flyway/sql:ro" \
        -v "${REPO_ROOT}/migrations/flyway/conf:/flyway/conf:ro" \
        flyway/flyway:11 \
        -url="jdbc:postgresql://localhost:5432/${dbname}" \
        -user="$DB_USER" \
        -password="$DB_PASSWORD" \
        -connectRetries=10 \
        migrate

    # Write .env.test.local
    _write_env_local "$slug" "$container" "$port" "$dbname"

    echo ""
    echo "Ready. Run DB-only integration tests with:"
    echo "    make test-integration-db"
}

cmd_down() {
    local slug container
    slug=$(branch_slug)
    container=$(container_name "$slug")

    if docker ps -a --format '{{.Names}}' | grep -q "^${container}$"; then
        docker rm -f "$container" >/dev/null
        echo "Removed container: ${container}"
    else
        echo "No container found: ${container}"
    fi

    # Remove the data volume
    docker volume rm "${container}-data" 2>/dev/null && echo "Removed volume: ${container}-data" || true

    # Remove .env.test.local if it references this container
    if [ -f "$ENV_LOCAL_FILE" ] && grep -q "Container: ${container}" "$ENV_LOCAL_FILE" 2>/dev/null; then
        rm -f "$ENV_LOCAL_FILE"
        echo "Removed: .env.test.local"
    fi
}

cmd_down_all() {
    local removed=0

    # Remove all running and stopped testpg containers
    while IFS= read -r name; do
        if [ -n "$name" ]; then
            docker rm -f "$name" >/dev/null
            echo "Removed container: ${name}"
            # Remove associated data volume
            docker volume rm "${name}-data" 2>/dev/null && echo "Removed volume: ${name}-data" || true
            removed=$((removed + 1))
        fi
    done < <(docker ps -a --filter "name=${CONTAINER_PREFIX}-" --format "{{.Names}}" 2>/dev/null || true)

    if [ "$removed" -eq 0 ]; then
        echo "No test DB containers found."
    else
        echo "Removed ${removed} container(s)."
    fi

    # Remove .env.test.local since whatever it pointed to is gone
    if [ -f "$ENV_LOCAL_FILE" ]; then
        rm -f "$ENV_LOCAL_FILE"
        echo "Removed: .env.test.local"
    fi
}

cmd_status() {
    echo "Branch test DB containers:"
    echo ""

    local found=0
    while IFS= read -r line; do
        if [ -n "$line" ]; then
            found=1
            echo "  $line"
        fi
    done < <(docker ps --filter "name=${CONTAINER_PREFIX}-" --format "table {{.Names}}\t{{.Ports}}\t{{.Status}}" 2>/dev/null || true)

    if [ "$found" -eq 0 ]; then
        echo "  (none running)"
    fi

    echo ""
    if [ -f "$ENV_LOCAL_FILE" ]; then
        echo "Active .env.test.local:"
        grep -E '^(TEST_DB_PORT|TEST_DB_NAME|# Container)' "$ENV_LOCAL_FILE" | sed 's/^/  /'
    else
        echo "No .env.test.local found. Run: make test-db-up"
    fi
}

# ── Main ─────────────────────────────────────────────────────────────────────

case "${1:-}" in
    up)       cmd_up ;;
    down)     cmd_down ;;
    down-all) cmd_down_all ;;
    status)   cmd_status ;;
    *)
        echo "Usage: $0 {up|down|down-all|status}"
        echo ""
        echo "  up        Start per-branch test PostgreSQL + run migrations"
        echo "  down      Stop and remove the container for the current branch"
        echo "  down-all  Stop and remove ALL test DB containers"
        echo "  status    Show running test DB containers"
        exit 1
        ;;
esac
