"""
Integration tests for Task Post-Completion Hooks.

Tests the complete flow:
1. Create task with Cy script using enrich_alert to add ai_analysis
2. Execute the task with TaskExecutionService
3. Verify ai_analysis_title is auto-generated by the post-hook

This validates that:
- enrich_alert properly adds enrichments under the task's cy_name
- Post-hooks are invoked after successful task execution
- ai_analysis_title is generated from ai_analysis via LLM call
- Artifact capture works during title generation

Uses the execute_single_task(task_run_id, tenant_id) API.
"""

from unittest.mock import AsyncMock
from uuid import uuid4

import pytest
from sqlalchemy.ext.asyncio import AsyncSession

from analysi.repositories.task import TaskRepository
from analysi.schemas.task_execution import TaskExecutionResult, TaskExecutionStatus
from analysi.services.task_execution import TaskExecutionService
from analysi.services.task_run import TaskRunService
from tests.utils.cy_output import parse_cy_output


async def _create_task_and_run(
    session: AsyncSession,
    tenant_id: str,
    *,
    task_name: str,
    cy_name: str,
    cy_script: str,
    input_data: dict,
    directive: str | None = None,
) -> tuple:
    """Helper: create a Task + TaskRun in the DB, return (task, task_run)."""
    task_repo = TaskRepository(session)
    task = await task_repo.create(
        {
            "tenant_id": tenant_id,
            "name": task_name,
            "description": "Test task for post-hooks",
            "cy_name": cy_name,
            "script": cy_script,
            "directive": directive,
            "function": "reasoning",
            "scope": "processing",
        }
    )
    await session.commit()

    task_run_service = TaskRunService()
    task_run = await task_run_service.create_execution(
        session=session,
        tenant_id=tenant_id,
        task_id=task.component_id,
        cy_script=None,  # loaded from task
        input_data=input_data,
        executor_config=None,
    )
    await session.commit()
    return task, task_run


@pytest.mark.integration
class TestTaskPostHooksIntegration:
    """Integration tests for post-task completion hooks with enrich_alert."""

    @pytest.mark.asyncio
    async def test_enrich_alert_adds_ai_analysis_and_post_hook_generates_title(
        self, integration_test_session: AsyncSession
    ):
        """
        End-to-end test: enrich_alert adds ai_analysis, post-hook generates title.

        Flow:
        1. Cy script calls enrich_alert(alert, {..., ai_analysis: "..."})
        2. TaskExecutionService runs the script
        3. Post-hook detects ai_analysis in enrichments[cy_name]
        4. Post-hook calls LLM (mocked) to generate ai_analysis_title
        5. Title is added to enrichments[cy_name]

        This test runs the REAL post-hook logic, only mocking the LLM call.
        """
        tenant_id = f"test-post-hooks-{uuid4().hex[:8]}"

        cy_script = """
alert = input
ip_address = "8.8.8.8"

analysis_result = {
    "ip": ip_address,
    "verdict": "clean",
    "confidence": 0.95,
    "ai_analysis": "This IP address shows zero malicious indicators.",
    "threat_score": 5,
    "categories": []
}

enriched_alert = enrich_alert(alert, analysis_result)

return enriched_alert
"""
        input_alert = {
            "title": "Suspicious Network Traffic",
            "severity": "medium",
            "indicators": {"ip": "8.8.8.8"},
            "source": "network_monitor",
        }

        _task, task_run = await _create_task_and_run(
            integration_test_session,
            tenant_id,
            task_name="IP Analysis Task",
            cy_name="ip_analysis",
            cy_script=cy_script,
            input_data=input_alert,
            directive="You are a security analyst. Summarize threat analysis results concisely.",
        )

        # Mock LLM functions - the real post-hook will use these
        llm_generated_title = "Clean IP - No Malicious Indicators Detected"
        mock_llm_summarize = AsyncMock(return_value=llm_generated_title)
        mock_llm_functions = {
            "llm_run": AsyncMock(return_value="mocked llm response"),
            "llm_summarize": mock_llm_summarize,
        }

        service = TaskExecutionService()

        # Patch _load_llm_functions on the executor to return our mock LLM
        original_load_llm = service.executor._load_llm_functions

        async def mock_load_llm_functions(execution_context):
            return mock_llm_functions

        service.executor._load_llm_functions = mock_load_llm_functions

        try:
            result = await service.execute_single_task(task_run.id, tenant_id)
        finally:
            service.executor._load_llm_functions = original_load_llm

        assert isinstance(result, TaskExecutionResult)
        assert result.status == TaskExecutionStatus.COMPLETED, (
            f"Expected COMPLETED, got {result.status}: {result.error_message}"
        )

        output_dict = parse_cy_output(result.output_data)
        assert isinstance(output_dict, dict), (
            f"Expected dict output, got {type(output_dict)}"
        )

        # Verify enrichments structure
        assert "enrichments" in output_dict, "Output should have enrichments"
        enrichments = output_dict["enrichments"]
        assert "ip_analysis" in enrichments, (
            f"Enrichments should contain 'ip_analysis' key, got: {list(enrichments.keys())}"
        )

        task_enrichment = enrichments["ip_analysis"]
        assert "ai_analysis" in task_enrichment, "Enrichment should contain ai_analysis"

        # CRITICAL: Verify post-hook added ai_analysis_title next to ai_analysis
        assert "ai_analysis_title" in task_enrichment, (
            "Post-hook should have added ai_analysis_title next to ai_analysis. "
            f"Got enrichment keys: {list(task_enrichment.keys())}"
        )
        assert task_enrichment["ai_analysis_title"] == llm_generated_title

        # Verify llm_summarize was actually called by the post-hook
        mock_llm_summarize.assert_called_once()

        # Verify the original alert data is preserved
        assert output_dict.get("title") == "Suspicious Network Traffic"
        assert output_dict.get("severity") == "medium"

    @pytest.mark.asyncio
    async def test_enrich_alert_output_structure(
        self, integration_test_session: AsyncSession
    ):
        """
        Test that enrich_alert properly structures output with enrichments.

        Verifies that:
        1. Task executes successfully
        2. Output contains enrichments keyed by cy_name (ip_analysis)
        3. Original alert fields are preserved
        """
        tenant_id = f"test-post-hooks-{uuid4().hex[:8]}"

        cy_script = """
alert = input
ip_address = "8.8.8.8"

analysis_result = {
    "ip": ip_address,
    "verdict": "clean",
    "confidence": 0.95,
    "ai_analysis": "This IP address shows zero malicious indicators.",
    "threat_score": 5,
    "categories": []
}

enriched_alert = enrich_alert(alert, analysis_result)

return enriched_alert
"""
        input_alert = {
            "title": "Suspicious DNS Query",
            "severity": "low",
        }

        _task, task_run = await _create_task_and_run(
            integration_test_session,
            tenant_id,
            task_name="IP Analysis Task",
            cy_name="ip_analysis",
            cy_script=cy_script,
            input_data=input_alert,
        )

        service = TaskExecutionService()
        result = await service.execute_single_task(task_run.id, tenant_id)

        assert result.status == TaskExecutionStatus.COMPLETED, (
            f"Task should succeed, got {result.status}: {result.error_message}"
        )

        output_dict = parse_cy_output(result.output_data)
        assert isinstance(output_dict, dict)

        # Verify enrichments are present
        assert "enrichments" in output_dict, "Output should have enrichments"
        enrichments = output_dict["enrichments"]

        # cy_name is "ip_analysis" - enrichments should be keyed by this
        assert "ip_analysis" in enrichments, (
            f"Enrichments should have 'ip_analysis' key, got: {list(enrichments.keys())}"
        )

        # Verify enrichment content
        task_enrichment = enrichments["ip_analysis"]
        assert task_enrichment["verdict"] == "clean"
        assert (
            task_enrichment["ai_analysis"]
            == "This IP address shows zero malicious indicators."
        )

        # Verify original alert preserved
        assert output_dict.get("title") == "Suspicious DNS Query"
        assert output_dict.get("severity") == "low"


@pytest.mark.integration
class TestEnrichAlertFunction:
    """Integration tests for enrich_alert Cy function."""

    @pytest.mark.asyncio
    async def test_enrich_alert_adds_data_under_cy_name(
        self, integration_test_session: AsyncSession
    ):
        """Verify enrich_alert adds enrichments keyed by task's cy_name."""
        tenant_id = f"test-enrich-{uuid4().hex[:8]}"

        cy_script = """
alert = input

# Add simple enrichment data
enrichment_data = {
    "source": "test_task",
    "score": 85,
    "details": "This is a test enrichment"
}

result = enrich_alert(alert, enrichment_data)
return result
"""
        input_alert = {"title": "Test Alert", "severity": "high"}

        _task, task_run = await _create_task_and_run(
            integration_test_session,
            tenant_id,
            task_name="Simple Enrichment Task",
            cy_name="simple_enrichment",
            cy_script=cy_script,
            input_data=input_alert,
        )

        service = TaskExecutionService()
        result = await service.execute_single_task(task_run.id, tenant_id)

        assert result.status == TaskExecutionStatus.COMPLETED, (
            f"Expected COMPLETED, got {result.status}: {result.error_message}"
        )

        output_dict = parse_cy_output(result.output_data)
        assert isinstance(output_dict, dict)

        # Verify enrichments structure
        assert "enrichments" in output_dict
        enrichments = output_dict["enrichments"]

        # Key insight: enrich_alert uses cy_name from execution context
        # The cy_name is set when task execution starts
        assert "simple_enrichment" in enrichments, (
            f"Expected 'simple_enrichment' in enrichments, got: {list(enrichments.keys())}"
        )

        enrichment = enrichments["simple_enrichment"]
        assert enrichment["source"] == "test_task"
        assert enrichment["score"] == 85

        # Original alert data preserved
        assert output_dict["title"] == "Test Alert"
        assert output_dict["severity"] == "high"
