"""
Integration test for Cy language InterpolationNode support.

Tests that string interpolation (${variable} syntax) works correctly
in Cy scripts during type inference.

This test was written to verify the fix for the InterpolationNode bug
identified during dogfooding (Finding #3 in DOGFOODING_FINDINGS.md).

Bug: Cy's analyze_types() didn't support InterpolationNode AST type,
causing type inference to fail for any script with string interpolation.

Impact: Blocked validation of 87% of tasks (20/23).

Expected behavior after fix (cy-language 0.19.1+):
- Scripts with string interpolation should successfully pass type inference
- Workflow validation should work with tasks containing interpolation
"""

import pytest

from analysi.models.task import Task, TaskFunction
from analysi.services.type_propagation.errors import TypePropagationError
from analysi.services.type_propagation.task_inference import infer_task_output_schema


@pytest.mark.integration
@pytest.mark.asyncio
class TestInterpolationNodeSupport:
    """Test that Cy correctly handles string interpolation in scripts."""

    @pytest.mark.asyncio
    async def test_script_with_string_interpolation(self):
        """
        Test that scripts with string interpolation (${variable}) work correctly.

        This reproduces the InterpolationNode bug:
        - Before fix (cy-language < 0.19.1): ValueError: Unsupported node type for type inference: InterpolationNode
        - After fix (cy-language >= 0.19.1): Should successfully infer types

        The bug occurred because Cy's analyze_types() didn't recognize InterpolationNode
        AST nodes generated by the ${variable} syntax.
        """
        # Create task with string interpolation (the problematic case)
        task = Task(
            component_id="test-component-id",
            directive="Analyze IP address with context",
            script="""
# Input fields
ip_address = input["ip"]
context = input["context"]

# String interpolation - this creates InterpolationNode in Cy AST
prompt = "Analyze this IP: ${ip_address} in context: ${context}"

# Return structured result
return {
    "ip": ip_address,
    "context": context,
    "prompt": prompt
}
""",
            function=TaskFunction.REASONING,
        )

        # Input schema with required fields
        input_schema = {
            "type": "object",
            "properties": {"ip": {"type": "string"}, "context": {"type": "string"}},
            "required": ["ip", "context"],
        }

        # Call type inference - this should NOT fail with InterpolationNode error
        output = await infer_task_output_schema(task, input_schema)

        # Should NOT be an error
        assert not isinstance(output, TypePropagationError), (
            f"Expected successful type inference, but got error: {output.message if isinstance(output, TypePropagationError) else output}"
        )

        # Should return object type (since we return a dict)
        assert output.get("type") == "object", (
            f"Expected output type 'object', got: {output}"
        )

    @pytest.mark.asyncio
    async def test_script_without_interpolation_still_works(self):
        """
        Control test: Verify that scripts WITHOUT interpolation still work.

        This ensures our fix didn't break existing functionality.
        """
        # Create task WITHOUT string interpolation (control case)
        task = Task(
            component_id="test-component-id",
            directive="Extract IP from input",
            script="""
ip_address = input["ip"]
context = input["context"]

# No interpolation - just string concatenation
prompt = "Analyze this IP: " + ip_address + " in context: " + context

return {
    "ip": ip_address,
    "context": context,
    "prompt": prompt
}
""",
            function=TaskFunction.EXTRACTION,
        )

        # Input schema
        input_schema = {
            "type": "object",
            "properties": {"ip": {"type": "string"}, "context": {"type": "string"}},
        }

        # Call type inference
        output = await infer_task_output_schema(task, input_schema)

        # Should work fine (this always worked)
        assert not isinstance(output, TypePropagationError)
        assert output.get("type") == "object"

    @pytest.mark.asyncio
    async def test_multiple_interpolations_in_script(self):
        """
        Test script with multiple string interpolations.

        Ensures the fix handles multiple InterpolationNode instances correctly.
        """
        task = Task(
            component_id="test-component-id",
            directive="Process alert with multiple interpolations",
            script="""
alert_id = input["alert_id"]
severity = input["severity"]
source_ip = input["source_ip"]
dest_ip = input["dest_ip"]

# Multiple interpolations
title = "Alert ${alert_id}: ${severity}"
description = "Traffic from ${source_ip} to ${dest_ip}"
summary = "Alert ${alert_id} - Severity: ${severity} - ${source_ip} -> ${dest_ip}"

return {
    "title": title,
    "description": description,
    "summary": summary
}
""",
            function=TaskFunction.REASONING,
        )

        # Input schema
        input_schema = {
            "type": "object",
            "properties": {
                "alert_id": {"type": "string"},
                "severity": {"type": "string"},
                "source_ip": {"type": "string"},
                "dest_ip": {"type": "string"},
            },
        }

        # Call type inference
        output = await infer_task_output_schema(task, input_schema)

        # Should handle multiple interpolations
        assert not isinstance(output, TypePropagationError), (
            f"Failed with multiple interpolations: {output.message if isinstance(output, TypePropagationError) else output}"
        )
        assert output.get("type") == "object"

    @pytest.mark.asyncio
    async def test_nested_interpolation_with_expressions(self):
        """
        Test interpolation with more complex expressions.

        Ensures the fix works with interpolated expressions, not just simple variables.
        """
        task = Task(
            component_id="test-component-id",
            directive="Format complex output",
            script="""
data = input["data"]
count = input["count"]

# Interpolation with expressions
message = "Found ${count} items in ${data['category']}"

return {
    "message": message,
    "count": count
}
""",
            function=TaskFunction.REASONING,
        )

        # Input schema
        input_schema = {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {"category": {"type": "string"}},
                },
                "count": {"type": "number"},
            },
        }

        # Call type inference
        output = await infer_task_output_schema(task, input_schema)

        # Should work with complex interpolations
        assert not isinstance(output, TypePropagationError), (
            f"Failed with nested interpolation: {output.message if isinstance(output, TypePropagationError) else output}"
        )
        assert output.get("type") == "object"
