"""
Integration tests for the single-file baseline migration (V001__baseline.sql).

Two regression tests cover bugs found during the audit of deleted migrations:
1. ``test_no_reference_to_dropped_partman_function``:
   V095 removed calls to ``partman.check_missing()`` (it does not exist in
   pg_partman v5.4). When the migration chain was collapsed into a single
   baseline, the V094 pg_cron health-check script was reintroduced verbatim,
   regressing the V095 fix. The daily 06:00 UTC cron job would then fail
   silently every night.
2. ``test_no_reference_to_dropped_integration_runs_table``:
   V121 dropped ``integration_runs``. pg_dump captured a dead function
   ``create_integration_runs_partition`` that referenced the dropped table
   via dynamic SQL (undetectable by Postgres at CREATE time). Calling the
   function would fail, and its presence in the baseline is a static-analysis
   hazard for readers.

Also:
3. ``test_seed_row_counts``: guards the four sets of migration-seeded rows
   (dispositions, node_templates, users, tenants) against accidental removal
   when the baseline is regenerated by ``build_baseline.sh``.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

pytestmark = [pytest.mark.integration]


BASELINE_PATH = (
    Path(__file__).resolve().parents[2]
    / "migrations"
    / "flyway"
    / "sql"
    / "V001__baseline.sql"
)


@pytest.fixture(scope="module")
def baseline_sql() -> str:
    assert BASELINE_PATH.exists(), f"baseline not found at {BASELINE_PATH}"
    return BASELINE_PATH.read_text()


def test_baseline_is_single_file_migration():
    """Only V001__baseline.sql should live in the migrations directory."""
    sql_files = sorted(BASELINE_PATH.parent.glob("V*.sql"))
    assert [f.name for f in sql_files] == ["V001__baseline.sql"], (
        f"Expected a single baseline migration, found: {[f.name for f in sql_files]}"
    )


def test_no_reference_to_dropped_partman_function(baseline_sql: str):
    """Regression: V095 removed ``partman.check_missing()``; baseline must not
    reintroduce it. pg_partman v5.4 does not expose this function — the
    scheduled cron job fails every run if the reference survives.
    """
    matches = re.findall(r"\bpartman\.check_missing\b", baseline_sql)
    assert not matches, (
        "baseline references partman.check_missing() — removed in V095 because "
        "it does not exist in pg_partman v5.4. Daily pg-partman-health-check "
        "cron job will fail silently. Use partman.check_default() only."
    )


def test_no_reference_to_dropped_integration_runs_table(baseline_sql: str):
    """Regression: V121 dropped ``integration_runs``. Any surviving SQL that
    names it (outside comments) is dead code that would fail if executed.
    """
    # Strip single-line comments so we only lint real SQL.
    lines = [
        ln
        for ln in baseline_sql.splitlines()
        if not ln.lstrip().startswith("--")
    ]
    body = "\n".join(lines)
    offenders = [
        ln for ln in lines if re.search(r"\bintegration_runs\b", ln)
    ]
    assert not offenders, (
        "baseline references the integration_runs table in executable SQL. "
        "V121 dropped this table. Offending lines:\n  "
        + "\n  ".join(offenders[:10])
    )
    # Also make sure no create_parent call tries to register it with partman.
    assert "public.integration_runs" not in body, (
        "baseline still registers public.integration_runs with pg_partman"
    )


def test_baseline_declares_required_seeds(baseline_sql: str):
    """The baseline must contain INSERT blocks for the four seed tables.

    Uses static analysis rather than a live DB count because integration
    tests truncate seed tables between runs. This is a regeneration
    safeguard: if ``build_baseline.sh`` drops a seed section, the test
    fails at the source rather than at runtime.

    Expected seeds (from deleted migrations V085, V107, V013→V015, V008+V044):
      * users       — 2 sentinel rows from V085
      * tenants     — 1 default row from V107
      * dispositions — 18 rows from V015 (replaces V013)
      * node_templates — 6 rows (3 demo from V008 + 3 system from V044)
    """
    required_inserts = {
        "users": r"INSERT\s+INTO\s+users\b",
        "tenants": r"INSERT\s+INTO\s+tenants\b",
        "dispositions": r"INSERT\s+INTO\s+public\.dispositions\b",
        "node_templates": r"INSERT\s+INTO\s+public\.node_templates\b",
    }
    missing = [name for name, pattern in required_inserts.items()
               if not re.search(pattern, baseline_sql)]
    assert not missing, (
        f"baseline missing seed INSERTs for: {missing}. "
        "Check build_baseline.sh — the seed section at the tail must produce "
        "rows for users, tenants, dispositions, and node_templates."
    )

    # Tighter check on row count per table — count INSERT VALUES lines for
    # pg_dump's single-row-per-INSERT format.
    disposition_rows = len(re.findall(r"INSERT INTO public\.dispositions VALUES", baseline_sql))
    node_template_rows = len(re.findall(r"INSERT INTO public\.node_templates VALUES", baseline_sql))
    assert disposition_rows == 18, (
        f"dispositions: expected 18 rows (V015 spec), found {disposition_rows}"
    )
    assert node_template_rows == 6, (
        f"node_templates: expected 6 rows (3 V008 demo + 3 V044 system), "
        f"found {node_template_rows}"
    )


@pytest.mark.asyncio
async def test_partman_health_check_executes_cleanly(integration_test_session):
    """The pg_cron health-check body must execute without error.

    This runs the same DO block the scheduled job runs — without pg_cron
    actually needing to be installed — so it catches typos, dropped function
    references, etc. before the 06:00 UTC schedule ever fires.
    """
    from sqlalchemy import text

    await integration_test_session.execute(
        text(
            """
            DO $inner$ BEGIN
              IF EXISTS (SELECT 1 FROM partman.check_default()) THEN
                RAISE WARNING 'pg_partman: data found in default partitions';
              END IF;
            END $inner$;
            """
        )
    )
    # If the block raised, the session would have rolled back and the call above
    # would have thrown.
