"""
3Ac26C7F-Baa4-4583-86Ff-5Aac82778A86 integration actions.

Auto-generated by Naxos Migrator.
"""

import contextlib
import os
from pathlib import Path
from typing import Any

import httpx

from analysi.integrations.framework.base import IntegrationAction

# Directories from which integration tools are allowed to read files for upload.
# Artifacts are staged under /tmp by the platform before integrations access them.
# Resolve the prefix so symlinks (e.g. macOS /tmp → /private/tmp) are handled.
_ALLOWED_FILE_PREFIXES = tuple(
    str(Path(p).resolve())
    for p in ("/tmp",)  # nosec B108 — artifact staging allowlist, not a temp file
)

class HealthCheckAction(IntegrationAction):
    """Health check for Slack integration"""

    async def execute(self, **kwargs) -> dict[str, Any]:
        """Tests authorization with Slack

        Returns:
            Result with status and data or error"""

        # Retrieve credentials
        bot_token = self.credentials.get("bot_token")
        if not bot_token:
            return {
                "healthy": False,
                "status": "error",
                "error": "Missing bot_token in credentials",
                "error_type": "ConfigurationError",
            }

        # Retrieve settings
        timeout = self.settings.get("timeout", 30)

        try:
            endpoint = "https://slack.com/api/auth.test"

            headers = {
                "Authorization": f"Bearer {bot_token}",
                "Accept": "application/json",
                "Content-Type": "application/x-www-form-urlencoded",
            }

            response = await self.http_request(
                endpoint,
                method="POST",
                headers=headers,
                data={},
                timeout=timeout,
            )

            data = response.json()

            if not isinstance(data, dict):
                return {
                    "healthy": False,
                    "status": "error",
                    "error": "Invalid response format from Slack API",
                    "error_type": "InvalidResponseError",
                }

            if not data.get("ok", False):
                return {
                    "healthy": False,
                    "status": "error",
                    "error": data.get("error", "Slack API returned ok=false"),
                    "error_type": "SlackAPIError",
                    "data": data,
                }

            return {
                "healthy": True,
                "status": "success",
                "message": f"Auth check to Slack passed. Configured for team: {data.get('team', 'Unknown Team')}",
                "data": {
                    "healthy": True,
                    "team": data.get("team"),
                    "team_id": data.get("team_id"),
                    "user": data.get("user"),
                    "user_id": data.get("user_id"),
                    "url": data.get("url"),
                    "bot_id": data.get("bot_id"),
                    "full_response": data,
                },
            }

        except httpx.HTTPStatusError as e:
            return {
                "healthy": False,
                "status": "error",
                "error": f"HTTP error occurred: {e!s}",
                "error_type": "HTTPStatusError",
            }
        except httpx.RequestError as e:
            return {
                "healthy": False,
                "status": "error",
                "error": f"Request error occurred: {e!s}",
                "error_type": "RequestError",
            }
        except httpx.TimeoutException as e:
            return {
                "healthy": False,
                "status": "error",
                "error": f"Request timed out: {e!s}",
                "error_type": "TimeoutException",
            }

class CreateChannelAction(IntegrationAction):
    """Create a new Slack channel"""

    async def execute(self, **kwargs) -> dict[str, Any]:
        """Create a new Slack channel

        Args:
            **kwargs: Must contain:
                - name (string): Name of channel
                - channel_type (string): Type of channel to create (public or private)

        Returns:
            Result with status and data or error"""
        # Extract parameters
        name = kwargs.get("name")
        channel_type = kwargs.get("channel_type")

        # Validate required parameters
        if not name:
            return {
                "status": "error",
                "error": "Missing required parameter: name",
                "error_type": "ValidationError",
            }

        # Retrieve credentials (user_token preferred, bot_token as fallback)
        token = self.credentials.get("user_token") or self.credentials.get("bot_token")
        if not token:
            return {
                "status": "error",
                "error": "Missing user_token or bot_token in credentials",
                "error_type": "ConfigurationError",
            }

        # Retrieve settings
        timeout = self.settings.get("timeout", 30)

        try:
            endpoint = "https://slack.com/api/conversations.create"

            headers = {
                "Authorization": f"Bearer {token}",
                "Content-Type": "application/json; charset=utf-8",
            }

            normalized_channel_type = (
                str(channel_type).strip().lower() if channel_type else "public"
            )
            if normalized_channel_type not in ["public", "private"]:
                return {
                    "status": "error",
                    "error": "Invalid channel_type. Must be 'public' or 'private'",
                    "error_type": "ValidationError",
                }

            payload: dict[str, Any] = {
                "name": name,
                "validate": True,
            }
            if normalized_channel_type == "private":
                payload["is_private"] = True

            response = await self.http_request(
                endpoint,
                method="POST",
                headers=headers,
                json_data=payload,
                timeout=timeout,
            )

            data = response.json()

            if not data.get("ok", False):
                error_code = data.get("error", "unknown_error")

                # Handle name_taken: return channel name as destination
                # send_message accepts #channel-name format directly
                if error_code == "name_taken":
                    return {
                        "status": "success",
                        "channel_id": f"#{name}",
                        "channel_name": name,
                        "is_private": False,
                        "already_existed": True,
                    }

                error_details = None
                metadata = data.get("response_metadata", {})
                messages = metadata.get("messages") or []
                if isinstance(messages, list) and messages:
                    error_details = "; ".join([str(m) for m in messages])

                error_message = f"Slack channel creation failed: {error_code}"
                if error_details:
                    error_message = f"{error_message}. Details: {error_details}"

                return {
                    "status": "error",
                    "error": error_message,
                    "error_type": "SlackAPIError",
                }

            channel = data.get("channel", {})
            return {
                "status": "success",
                "channel_id": channel.get("id"),
                "channel_name": channel.get("name"),
                "is_private": channel.get("is_private"),
                "full_data": data,
            }

        except httpx.HTTPStatusError as e:
            return {
                "status": "error",
                "error": f"HTTP error occurred: {e!s}",
                "error_type": "HTTPStatusError",
            }
        except httpx.RequestError as e:
            return {
                "status": "error",
                "error": f"Request error occurred: {e!s}",
                "error_type": "RequestError",
            }
        except httpx.TimeoutException as e:
            return {
                "status": "error",
                "error": f"Request timed out: {e!s}",
                "error_type": "TimeoutException",
            }

class ListChannelsAction(IntegrationAction):
    """List public channels of a Slack team"""

    async def execute(self, **kwargs) -> dict[str, Any]:
        """List public channels of a Slack team

        Args:
            **kwargs: Must contain:
                - limit (integer): Specify the maximum number of results to return. Default is 100

        Returns:
            Result with status and data or error"""
        # Extract parameters
        limit = kwargs.get("limit")

        # Retrieve credentials
        bot_token = self.credentials.get("bot_token")
        if not bot_token:
            return {
                "status": "error",
                "error": "Missing bot_token in credentials",
                "error_type": "ConfigurationError",
            }

        # Retrieve settings
        timeout = self.settings.get("timeout", 30)

        try:
            endpoint = "https://slack.com/api/conversations.list"

            # Construct request headers and parameters
            headers = {
                "Authorization": f"Bearer {bot_token}",
                "Accept": "application/json",
                "Content-Type": "application/json",
            }
            try:
                limit_value = int(limit) if limit is not None else 100
                if limit_value <= 0:
                    limit_value = 100
            except (TypeError, ValueError):
                limit_value = 100
            params = {
                "limit": limit_value,
                "types": "public_channel",
                "exclude_archived": True,
            }

            response = await self.http_request(
                endpoint,
                headers=headers,
                params=params,
                timeout=timeout,
            )

            # Parse response and extract meaningful data
            data = response.json()
            if not data.get("ok", False):
                return {
                    "status": "error",
                    "error": data.get("error", "Unknown error from Slack API"),
                    "error_type": "SlackAPIError",
                    "full_data": data,
                }

            channels = data.get("channels", [])
            for chan in channels:
                name = chan.get("name", "unknownchannel")
                chan["name"] = f"#{name}"

            return {
                "status": "success",
                "num_public_channels": len(channels),
                "channels": channels,
                "response_metadata": data.get("response_metadata", {}),
                "full_data": data,
            }

        except httpx.HTTPStatusError as e:
            return {
                "status": "error",
                "error": f"HTTP error occurred: {e!s}",
                "error_type": "HTTPStatusError",
            }
        except httpx.RequestError as e:
            return {
                "status": "error",
                "error": f"Request error occurred: {e!s}",
                "error_type": "RequestError",
            }
        except httpx.TimeoutException as e:
            return {
                "status": "error",
                "error": f"Request timed out: {e!s}",
                "error_type": "TimeoutException",
            }

class ListUsersAction(IntegrationAction):
    """List users of a Slack team"""

    async def execute(self, **kwargs) -> dict[str, Any]:
        """List users of a Slack team

        Args:
            **kwargs: Must contain:
                - limit (integer): Specify the maximum number of results to return. Default is 100

        Returns:
            Result with status and data or error"""
        # Extract parameters
        limit = kwargs.get("limit")

        # Retrieve credentials
        bot_token = self.credentials.get("bot_token")
        if not bot_token:
            return {
                "status": "error",
                "error": "Missing bot_token in credentials",
                "error_type": "ConfigurationError",
            }

        # Retrieve settings
        timeout = self.settings.get("timeout", 30)

        try:
            endpoint = "https://slack.com/api/users.list"

            headers = {
                "Authorization": f"Bearer {bot_token}",
                "Accept": "application/json",
            }

            # Determine effective limit and per-page size
            default_limit = 100
            max_page_size = 200
            try:
                effective_limit = int(limit) if limit is not None else default_limit
            except (TypeError, ValueError):
                effective_limit = default_limit
            if effective_limit <= 0:
                effective_limit = default_limit

            users_collected: list[dict] = []
            next_cursor: str | None = None
            remaining = effective_limit
            cursor: str | None = None

            while remaining > 0:
                page_size = min(max_page_size, remaining)
                params: dict[str, Any] = {"limit": page_size}
                if cursor:
                    params["cursor"] = cursor

                response = await self.http_request(
                    endpoint,
                    headers=headers,
                    params=params,
                    timeout=timeout,
                )

                data = response.json()
                if not data.get("ok", False):
                    return {
                        "status": "error",
                        "error": f"Slack API error: {data.get('error', 'unknown_error')}",
                        "error_type": "SlackAPIError",
                    }

                members = data.get("members", [])
                for user in members:
                    name = user.get("name", "unknownuser")
                    user["name"] = f"@{name}"
                users_collected.extend(members)
                remaining -= len(members)

                cursor = data.get("response_metadata", {}).get("next_cursor") or ""
                if not cursor:
                    next_cursor = None
                    break
                next_cursor = cursor

            limited_users = users_collected[:effective_limit]
            return {
                "status": "success",
                "users": limited_users,
                "num_users": len(limited_users),
                "full_data": {"members": limited_users, "next_cursor": next_cursor},
            }

        except httpx.HTTPStatusError as e:
            return {
                "status": "error",
                "error": f"HTTP error occurred: {e!s}",
                "error_type": "HTTPStatusError",
            }
        except httpx.RequestError as e:
            return {
                "status": "error",
                "error": f"Request error occurred: {e!s}",
                "error_type": "RequestError",
            }
        except httpx.TimeoutException as e:
            return {
                "status": "error",
                "error": f"Request timed out: {e!s}",
                "error_type": "TimeoutException",
            }

def _validate_email_address_safe(email: str | None) -> tuple[bool, str]:
    """Validate email address format.

    Args:
        email: Email address to validate

    Returns:
        Tuple of (is_valid, error_message)
    """
    # If no email provided, consider valid here; presence is validated later based on other params
    if not email:
        return True, ""
    if not isinstance(email, str):
        return False, "Email address must be a string"

    import re

    pattern = re.compile(r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$")
    if not pattern.match(email):
        return False, "Invalid email address format"

    return True, ""

class GetUserAction(IntegrationAction):
    """Get information about a user of a Slack team"""

    async def execute(self, **kwargs) -> dict[str, Any]:
        """Get information about a user of a Slack team

        Args:
            **kwargs: Must contain:
                - user_id (string): Unique ID of user to get info of
                - email_address (string): Email address of user to get info of. Will not be used if User ID is specified

        Returns:
            Result with status and data or error"""
        # Extract parameters
        user_id = kwargs.get("user_id")
        email_address = kwargs.get("email_address")

        # Validate parameter formats
        is_valid, error_msg = _validate_email_address_safe(email_address)
        if not is_valid:
            return {
                "status": "error",
                "error": error_msg,
                "error_type": "ValidationError",
            }

        # Retrieve credentials
        bot_token = self.credentials.get("bot_token")
        if not bot_token:
            return {
                "status": "error",
                "error": "Missing bot_token in credentials",
                "error_type": "ConfigurationError",
            }

        # Retrieve settings
        timeout = self.settings.get("timeout", 30)

        try:
            base_url = "https://slack.com/api"

            # Validate inputs: require either user_id or email_address
            if not user_id and not email_address:
                return {
                    "status": "error",
                    "error": "Either 'user_id' or 'email_address' must be provided",
                    "error_type": "ValidationError",
                }

            # If user_id is provided, validate its format per Slack conventions
            if user_id and not (
                str(user_id).startswith("U") or str(user_id).startswith("W")
            ):
                return {
                    "status": "error",
                    "error": "Invalid Slack user_id format. It should start with 'U' or 'W'",
                    "error_type": "ValidationError",
                }

            if user_id:
                endpoint = f"{base_url}/users.info"
                params = {"user": user_id}
                query_type = "user_id"
            else:
                endpoint = f"{base_url}/users.lookupByEmail"
                params = {"email": email_address}
                query_type = "email_address"

            headers = {
                "Authorization": f"Bearer {bot_token}",
                "Content-Type": "application/json",
            }

            response = await self.http_request(
                endpoint,
                headers=headers,
                params=params,
                timeout=timeout,
            )

            data = response.json()

            # Slack returns HTTP 200 with ok=false on application errors
            if not data.get("ok", False):
                slack_error = data.get("error", "Unknown error from Slack API")
                # Slack signals not-found via ok=false with specific error codes
                if slack_error in ("user_not_found", "users_not_found"):
                    return {
                        "status": "success",
                        "not_found": True,
                        "query_type": query_type,
                        "user_id": user_id,
                        "email": email_address,
                        "error_code": slack_error,
                    }
                return {
                    "status": "error",
                    "error": slack_error,
                    "error_type": "SlackAPIError",
                }

            user = data.get("user")
            if not user:
                return {
                    "status": "success",
                    "not_found": True,
                    "query_type": query_type,
                    "user_id": user_id,
                    "email": email_address,
                }

            profile = user.get("profile", {})

            return {
                "status": "success",
                "query_type": query_type,
                "user_id": user.get("id"),
                "username": user.get("name"),
                "user_mention": f"@{user.get('name', '')}"
                if user.get("name")
                else None,
                "real_name": user.get("real_name"),
                "email": profile.get("email"),
                "display_name": profile.get("display_name"),
                "team_id": user.get("team_id"),
                "tz": user.get("tz"),
                "deleted": user.get("deleted"),
                "is_bot": user.get("is_bot"),
                "full_data": data,
            }

        except httpx.HTTPStatusError as e:
            if e.response.status_code == 404:
                return {
                    "status": "success",
                    "not_found": True,
                    "query_type": query_type,
                    "user_id": user_id,
                    "email": email_address,
                }
            return {
                "status": "error",
                "error": f"HTTP error occurred: {e!s}",
                "error_type": "HTTPStatusError",
            }
        except httpx.RequestError as e:
            return {
                "status": "error",
                "error": f"Request error occurred: {e!s}",
                "error_type": "RequestError",
            }
        except httpx.TimeoutException as e:
            return {
                "status": "error",
                "error": f"Request timed out: {e!s}",
                "error_type": "TimeoutException",
            }

class InviteUsersAction(IntegrationAction):
    """Invite user(s) to a Slack channel"""

    async def execute(self, **kwargs) -> dict[str, Any]:
        """Invite user(s) to a Slack channel

        Args:
            **kwargs: Must contain:
                - channel_id (string): ID of channel
                - users (string): Comma-separated list of users (IDs) to invite

        Returns:
            Result with status and data or error"""
        # Extract parameters
        channel_id = kwargs.get("channel_id")
        users = kwargs.get("users")

        # Validate required parameters
        if not channel_id:
            return {
                "status": "error",
                "error": "Missing required parameter: channel_id",
                "error_type": "ValidationError",
            }
        if not users:
            return {
                "status": "error",
                "error": "Missing required parameter: users",
                "error_type": "ValidationError",
            }

        # Normalize and validate users list
        if isinstance(users, str):
            user_list = [u.strip() for u in users.split(",")]
        elif isinstance(users, list):
            user_list = [str(u).strip() for u in users]
        else:
            return {
                "status": "error",
                "error": "Invalid 'users' parameter type. Expected string or list of strings",
                "error_type": "ValidationError",
            }
        user_list = [u for u in user_list if u]
        if not user_list:
            return {
                "status": "error",
                "error": "Invalid 'users' parameter: no user IDs provided after parsing",
                "error_type": "ValidationError",
            }

        # Retrieve credentials (user_token preferred, bot_token as fallback)
        token = self.credentials.get("user_token") or self.credentials.get("bot_token")
        if not token:
            return {
                "status": "error",
                "error": "Missing user_token or bot_token in credentials",
                "error_type": "ConfigurationError",
            }

        # Retrieve settings
        timeout = self.settings.get("timeout", 30)

        try:
            endpoint = "https://slack.com/api/conversations.invite"

            headers = {
                "Authorization": f"Bearer {token}",
                "Content-Type": "application/json; charset=utf-8",
            }
            payload = {"channel": channel_id, "users": ",".join(user_list)}

            response = await self.http_request(
                endpoint,
                method="POST",
                headers=headers,
                json_data=payload,
                timeout=timeout,
            )

            data = response.json()

            if not data.get("ok", False):
                error = data.get("error", "unknown_error")
                details = data.get("detail") or data.get("response_metadata", {}).get(
                    "messages"
                )
                if details:
                    return {
                        "status": "error",
                        "error": f"Failed to invite users to channel: {error}. Details: {details}",
                        "error_type": "SlackAPIError",
                        "full_data": data,
                    }
                return {
                    "status": "error",
                    "error": f"Failed to invite users to channel: {error}",
                    "error_type": "SlackAPIError",
                    "full_data": data,
                }

            return {
                "status": "success",
                "channel_id": channel_id,
                "invited_users": user_list,
                "channel": data.get("channel"),
                "warnings": data.get("warning")
                or data.get("response_metadata", {}).get("warnings"),
                "full_data": data,
            }

        except httpx.HTTPStatusError as e:
            return {
                "status": "error",
                "error": f"HTTP error occurred: {e!s}",
                "error_type": "HTTPStatusError",
            }
        except httpx.RequestError as e:
            return {
                "status": "error",
                "error": f"Request error occurred: {e!s}",
                "error_type": "RequestError",
            }
        except httpx.TimeoutException as e:
            return {
                "status": "error",
                "error": f"Request timed out: {e!s}",
                "error_type": "TimeoutException",
            }

class SendMessageAction(IntegrationAction):
    """Send a message to Slack"""

    async def execute(self, **kwargs) -> dict[str, Any]:  # noqa: C901
        """Send a message to Slack

        Args:
            **kwargs: Must contain:
                - destination (string): Channel (e.g. #channel or C1A1A1AAA)
                - message (string): Message to send, required if 'blocks' is not set. If 'blocks' is set, this is used as fallback text
                - blocks (string): Blocks to send, required if 'message' is not set
                - parent_message_ts (string): Parent message timestamp to reply in thread
                - reply_broadcast (boolean): Used in conjunction with 'parent_message_ts' and indicates whether reply should be made visible to everyone in the channel or conversation
                - link_names (boolean): Check this if you want to enable announcements in your Slack messages using mentions. E.g.: Use @someone or @channel in your message in combination with this check to notify people

        Returns:
            Result with status and data or error"""
        # Extract parameters
        destination = kwargs.get("destination")
        message = kwargs.get("message")
        blocks = kwargs.get("blocks")
        parent_message_ts = kwargs.get("parent_message_ts")
        reply_broadcast = kwargs.get("reply_broadcast")
        link_names = kwargs.get("link_names")

        # Validate required parameters
        if not destination:
            return {
                "status": "error",
                "error": "Missing required parameter: destination",
                "error_type": "ValidationError",
            }

        # Retrieve credentials
        bot_token = self.credentials.get("bot_token")
        if not bot_token:
            return {
                "status": "error",
                "error": "Missing bot_token in credentials",
                "error_type": "ConfigurationError",
            }

        # Retrieve settings
        timeout = self.settings.get("timeout", 30)

        try:
            endpoint = "https://slack.com/api/chat.postMessage"

            headers = {
                "Authorization": f"Bearer {bot_token}",
                "Content-Type": "application/json; charset=utf-8",
                "Accept": "application/json",
            }

            # Require at least one of message or blocks
            if message is None and blocks is None:
                return {
                    "status": "error",
                    "error": "Either 'message' or 'blocks' must be provided",
                    "error_type": "ValidationError",
                }

            payload: dict[str, Any] = {
                "channel": destination,
            }

            if message is not None:
                try:
                    if "\\" in message:
                        message = bytes(message, "utf-8").decode("unicode_escape")
                except Exception:
                    # If decoding fails, use the original message
                    pass
                payload["text"] = message
            elif blocks is not None:
                # Provide minimal fallback text when only blocks are provided
                payload["text"] = " "

            if blocks is not None:
                payload["blocks"] = blocks

            if link_names is not None:
                payload["link_names"] = bool(link_names)
            else:
                payload["link_names"] = False

            if parent_message_ts is not None:
                payload["thread_ts"] = parent_message_ts
                if reply_broadcast is not None:
                    payload["reply_broadcast"] = bool(reply_broadcast)

            response = await self.http_request(
                endpoint,
                method="POST",
                headers=headers,
                json_data=payload,
                timeout=timeout,
            )

            data = response.json()

            if not data.get("ok", False):
                error_msg = (
                    data.get("error")
                    or data.get("warning")
                    or "Unknown Slack API error"
                )
                return {
                    "status": "error",
                    "error": f"Slack API error: {error_msg}",
                    "error_type": "SlackAPIError",
                    "full_data": data,
                }

            return {
                "status": "success",
                "channel": data.get("channel"),
                "ts": data.get("ts"),
                "message": data.get("message"),
                "full_data": data,
            }

        except httpx.HTTPStatusError as e:
            return {
                "status": "error",
                "error": f"HTTP error occurred: {e!s}",
                "error_type": "HTTPStatusError",
            }
        except httpx.RequestError as e:
            return {
                "status": "error",
                "error": f"Request error occurred: {e!s}",
                "error_type": "RequestError",
            }
        except httpx.TimeoutException as e:
            return {
                "status": "error",
                "error": f"Request timed out: {e!s}",
                "error_type": "TimeoutException",
            }

class AddReactionAction(IntegrationAction):
    """React to a message in Slack"""

    async def execute(self, **kwargs) -> dict[str, Any]:
        """React to a message in Slack

        Args:
            **kwargs: Must contain:
                - destination (string): Channel ID (C1A1A1AAA) to send message to
                - emoji (string): Reaction (emoji) to add
                - message_ts (string): Timestamp of the message to add reaction to

        Returns:
            Result with status and data or error"""
        # Extract parameters
        destination = kwargs.get("destination")
        emoji = kwargs.get("emoji")
        message_ts = kwargs.get("message_ts")

        # Validate required parameters
        if not destination:
            return {
                "status": "error",
                "error": "Missing required parameter: destination",
                "error_type": "ValidationError",
            }
        if not emoji:
            return {
                "status": "error",
                "error": "Missing required parameter: emoji",
                "error_type": "ValidationError",
            }
        if not message_ts:
            return {
                "status": "error",
                "error": "Missing required parameter: message_ts",
                "error_type": "ValidationError",
            }

        # Retrieve credentials
        bot_token = self.credentials.get("bot_token")
        if not bot_token:
            return {
                "status": "error",
                "error": "Missing bot_token in credentials",
                "error_type": "ConfigurationError",
            }

        # Retrieve settings
        timeout = self.settings.get("timeout", 30)

        try:
            endpoint = "https://slack.com/api/reactions.add"

            # Normalize emoji to just the name (strip surrounding colons if provided)
            emoji_name = emoji.strip(":") if isinstance(emoji, str) else emoji

            headers = {
                "Authorization": f"Bearer {bot_token}",
                "Content-Type": "application/x-www-form-urlencoded",
            }
            params = {
                "channel": destination,
                "name": emoji_name,
                "timestamp": message_ts,
            }

            response = await self.http_request(
                endpoint,
                method="POST",
                headers=headers,
                data=params,
                timeout=timeout,
            )

            data = response.json()

            if not data.get("ok", False):
                return {
                    "status": "error",
                    "error": f"Slack API error: {data.get('error', 'unknown_error')}",
                    "error_type": "SlackAPIError",
                    "full_data": data,
                }

            return {
                "status": "success",
                "destination": destination,
                "emoji": emoji_name,
                "message_ts": message_ts,
                "full_data": data,
            }

        except httpx.HTTPStatusError as e:
            return {
                "status": "error",
                "error": f"HTTP error occurred: {e!s}",
                "error_type": "HTTPStatusError",
            }
        except httpx.RequestError as e:
            return {
                "status": "error",
                "error": f"Request error occurred: {e!s}",
                "error_type": "RequestError",
            }
        except httpx.TimeoutException as e:
            return {
                "status": "error",
                "error": f"Request timed out: {e!s}",
                "error_type": "TimeoutException",
            }

class UploadFileAction(IntegrationAction):
    """Upload file to Slack"""

    async def execute(self, **kwargs) -> dict[str, Any]:  # noqa: C901
        """Upload file to Slack

        Args:
            **kwargs: Must contain:
                - destination (string): Channel (e.g. #channel or C1A1A1AAA) or user (e.g. @user or U1A1A1AAA) to upload to
                - parent_message_ts (string): Parent message timestamp to reply in thread
                - file (string): Vault ID of file to upload
                - content (string): Contents of the file
                - caption (string): Caption to add to the file
                - filetype (string): A file type identifier (https://api.slack.com/types/file#file_types)
                - filename (string): Name of the file

        Returns:
            Result with status and data or error"""
        # Extract parameters
        destination = kwargs.get("destination")
        parent_message_ts = kwargs.get("parent_message_ts")
        file = kwargs.get("file")
        content = kwargs.get("content")
        caption = kwargs.get("caption")
        filetype = kwargs.get("filetype")
        filename = kwargs.get("filename")

        # Validate required parameters
        if not destination:
            return {
                "status": "error",
                "error": "Missing required parameter: destination",
                "error_type": "ValidationError",
            }

        # Retrieve credentials
        bot_token = self.credentials.get("bot_token")
        if not bot_token:
            return {
                "status": "error",
                "error": "Missing bot_token in credentials",
                "error_type": "ConfigurationError",
            }

        # Retrieve settings
        timeout = self.settings.get("timeout", 30)

        try:
            # Validate that either a file path or content is provided
            if not file and not content:
                return {
                    "status": "error",
                    "error": "Either 'file' (path) or 'content' must be provided",
                    "error_type": "ValidationError",
                }

            endpoint = "https://slack.com/api/files.upload"

            headers = {
                "Authorization": f"Bearer {bot_token}",
            }

            data: dict[str, Any] = {
                "channels": destination,
            }
            if caption:
                data["initial_comment"] = caption
            if filetype:
                data["filetype"] = filetype
            if filename:
                data["filename"] = filename
            if parent_message_ts:
                data["thread_ts"] = parent_message_ts

            files_payload = None
            file_handle = None

            if file:
                # Security: validate the file path to prevent path traversal.
                # Resolve symlinks and ".." components, then verify the
                # canonical path is genuinely *inside* an allowed directory.
                # We use Path.is_relative_to (a real path-ancestry check) — a
                # naive str.startswith would accept sibling directories that
                # share a prefix string, e.g. "/tmp_evil/" vs "/tmp/".
                try:
                    resolved = Path(file).resolve(strict=False)
                except (ValueError, OSError):
                    return {
                        "status": "error",
                        "error": "Invalid file path",
                        "error_type": "ValidationError",
                    }

                if not any(
                    resolved.is_relative_to(prefix) for prefix in _ALLOWED_FILE_PREFIXES
                ):
                    return {
                        "status": "error",
                        "error": "Path traversal blocked: file must be under an allowed directory",
                        "error_type": "ValidationError",
                    }

                file_path = str(resolved)
                if not os.path.isfile(file_path):
                    return {
                        "status": "error",
                        "error": f"File not found at path: {file_path}",
                        "error_type": "ValidationError",
                    }
                upload_filename = (
                    filename or os.path.basename(file_path) or "upload.bin"
                )
                file_handle = open(file_path, "rb")  # noqa: SIM115
                files_payload = {
                    "file": (upload_filename, file_handle, "application/octet-stream")
                }
            else:
                data["content"] = content

            async with httpx.AsyncClient(timeout=timeout) as client:
                response = await client.post(
                    endpoint, headers=headers, data=data, files=files_payload
                )
                response.raise_for_status()

            # Ensure file handle is closed after the request
            if file_handle:
                with contextlib.suppress(Exception):
                    file_handle.close()

            resp_json = response.json()
            if not resp_json.get("ok", False):
                return {
                    "status": "error",
                    "error": resp_json.get("error", "Slack API returned ok=false"),
                    "error_type": "SlackAPIError",
                }

            file_json = resp_json.get("file", {}) or {}

            # Build thumbnails structure and normalize some fields similar to upstream implementation
            thumbnail_dict: dict[str, dict[str, Any]] = {}
            pop_list = []
            for key, value in list(file_json.items()):
                if isinstance(key, str) and key.startswith("thumb"):
                    pop_list.append(key)
                    name_arr = key.split("_")
                    if len(name_arr) >= 2:
                        thumb_name = f"{name_arr[0]}_{name_arr[1]}"
                        if thumb_name not in thumbnail_dict:
                            thumbnail_dict[thumb_name] = {}
                        if len(name_arr) == 2:
                            thumbnail_dict[thumb_name]["img_url"] = value
                        elif len(name_arr) >= 3:
                            if name_arr[2] == "w":
                                thumbnail_dict[thumb_name]["width"] = value
                            elif name_arr[2] == "h":
                                thumbnail_dict[thumb_name]["height"] = value
                elif key == "initial_comment":
                    # Slack may return initial_comment as string or object
                    if isinstance(value, dict):
                        resp_json["caption"] = value.get("comment") or value.get("text")
                    else:
                        resp_json["caption"] = value
                    pop_list.append(key)
                elif key in ["channels", "ims", "groups"]:
                    if "destinations" not in resp_json:
                        resp_json["destinations"] = []
                    if isinstance(value, list):
                        resp_json["destinations"] += value
                    pop_list.append(key)
                elif key == "username":
                    pop_list.append(key)
                elif key == "user":
                    resp_json["sender"] = value
                    pop_list.append(key)

            for poppee in pop_list:
                file_json.pop(poppee, None)

            resp_json["thumbnails"] = thumbnail_dict

            result: dict[str, Any] = {
                "status": "success",
                "destination": destination,
                "file": file_json,
                "thumbnails": thumbnail_dict,
                "full_data": resp_json,
            }

            # Convenience fields
            if file_json:
                result["file_id"] = file_json.get("id")
                result["file_name"] = file_json.get("name") or (
                    filename if filename else None
                )
                result["permalink"] = file_json.get("permalink") or file_json.get(
                    "permalink_public"
                )

            return result

        except httpx.HTTPStatusError as e:
            return {
                "status": "error",
                "error": f"HTTP error occurred: {e!s}",
                "error_type": "HTTPStatusError",
            }
        except httpx.RequestError as e:
            return {
                "status": "error",
                "error": f"Request error occurred: {e!s}",
                "error_type": "RequestError",
            }
        except httpx.TimeoutException as e:
            return {
                "status": "error",
                "error": f"Request timed out: {e!s}",
                "error_type": "TimeoutException",
            }

class AskQuestionAction(IntegrationAction):
    """Ask a question to a Slack user"""

    async def execute(self, **kwargs) -> dict[str, Any]:
        """Ask a question to a Slack user

        Args:
            **kwargs: Must contain:
                - destination (string): User (e.g. @user or U1A1A1AAA) to ask question to
                - question (string): Question to ask
                - responses (string): Comma separated string values for responses. (Maximum responses allowed are 5)
                - confirmation (string): Message to user after response

        Returns:
            Result with status and data or error"""
        # Extract parameters
        destination = kwargs.get("destination")
        question = kwargs.get("question")
        responses = kwargs.get("responses")
        kwargs.get("confirmation")

        # Validate required parameters
        if not destination:
            return {
                "status": "error",
                "error": "Missing required parameter: destination",
                "error_type": "ValidationError",
            }
        if not question:
            return {
                "status": "error",
                "error": "Missing required parameter: question",
                "error_type": "ValidationError",
            }

        # Retrieve credentials
        bot_token = self.credentials.get("bot_token")
        if not bot_token:
            return {
                "status": "error",
                "error": "Missing bot_token in credentials",
                "error_type": "ConfigurationError",
            }

        # Retrieve settings
        timeout = self.settings.get("timeout", 30)

        try:
            endpoint = "https://slack.com/api/chat.postMessage"

            headers = {
                "Authorization": f"Bearer {bot_token}",
                "Content-Type": "application/json; charset=utf-8",
            }

            # Prepare responses/buttons
            if responses and isinstance(responses, str):
                raw_items = [x.strip() for x in responses.split(",")]
                ordered_unique: list[str] = []
                seen = set()
                for item in raw_items:
                    if item and item not in seen:
                        ordered_unique.append(item)
                        seen.add(item)
                answer_texts = ordered_unique
            else:
                answer_texts = ["yes", "no"]

            if not answer_texts:
                answer_texts = ["yes", "no"]

            if len(answer_texts) > 5:
                return {
                    "status": "error",
                    "error": "Maximum 5 responses allowed",
                    "error_type": "ValidationError",
                }

            actions = [
                {"name": a, "text": a, "value": a, "type": "button"}
                for a in answer_texts
            ]

            attachments = [
                {
                    "text": question,
                    "fallback": "Interactive message cannot be displayed.",
                    "callback_id": "ask_question",
                    "color": "#422E61",
                    "attachment_type": "default",
                    "actions": actions,
                }
            ]

            payload: dict[str, Any] = {
                "channel": destination,
                "text": question,
                "attachments": attachments,
            }

            response = await self.http_request(
                endpoint,
                method="POST",
                headers=headers,
                json_data=payload,
                timeout=timeout,
            )

            data = response.json()

            if not data.get("ok", False):
                return {
                    "status": "error",
                    "error": f"Slack API error: {data.get('error', 'unknown_error')}",
                    "error_type": "SlackAPIError",
                }

            return {
                "status": "success",
                "channel": data.get("channel"),
                "ts": data.get("ts") or (data.get("message") or {}).get("ts"),
                "message": data.get("message"),
                "full_data": data,
            }

        except httpx.HTTPStatusError as e:
            return {
                "status": "error",
                "error": f"HTTP error occurred: {e!s}",
                "error_type": "HTTPStatusError",
            }
        except httpx.RequestError as e:
            return {
                "status": "error",
                "error": f"Request error occurred: {e!s}",
                "error_type": "RequestError",
            }
        except httpx.TimeoutException as e:
            return {
                "status": "error",
                "error": f"Request timed out: {e!s}",
                "error_type": "TimeoutException",
            }

class AskQuestionChannelAction(IntegrationAction):
    """Ask a question in slack channel"""

    async def execute(self, **kwargs) -> dict[str, Any]:  # noqa: C901
        """Ask a question in slack channel

        Args:
            **kwargs: Must contain:
                - destination (string): Channel (e.g. #channel-name or C1A1A1AAA) to ask question to
                - question (string): Question to ask
                - responses (string): Comma separated string values for responses. (Maximum responses allowed are 5)

        Returns:
            Result with status and data or error"""
        # Extract parameters
        destination = kwargs.get("destination")
        question = kwargs.get("question")
        responses = kwargs.get("responses")

        # Validate required parameters
        if not destination:
            return {
                "status": "error",
                "error": "Missing required parameter: destination",
                "error_type": "ValidationError",
            }
        if not question:
            return {
                "status": "error",
                "error": "Missing required parameter: question",
                "error_type": "ValidationError",
            }

        # Retrieve credentials
        bot_token = self.credentials.get("bot_token")
        if not bot_token:
            return {
                "status": "error",
                "error": "Missing bot_token in credentials",
                "error_type": "ConfigurationError",
            }

        # Retrieve settings
        timeout = self.settings.get("timeout", 30)

        try:
            # Reject direct user destinations to ensure messaging a channel only
            if destination.startswith("@") or destination.startswith("U"):
                return {
                    "status": "error",
                    "error": "Unable to send question to a user. Please provide a channel (e.g., #channel-name or C12345)",
                    "error_type": "ValidationError",
                }

            # Determine API endpoint
            endpoint = "https://slack.com/api/chat.postMessage"

            # Construct request headers
            headers = {
                "Authorization": f"Bearer {bot_token}",
                "Content-Type": "application/json",
                "Accept": "application/json",
            }

            # Parse and validate responses (optional)
            button_texts = []
            if isinstance(responses, str) and responses.strip():
                button_texts = [r.strip() for r in responses.split(",") if r.strip()]
                if len(button_texts) > 5:
                    return {
                        "status": "error",
                        "error": "Maximum responses allowed are 5",
                        "error_type": "ValidationError",
                    }

            # Build blocks if we have response options
            blocks = []
            if button_texts:
                blocks.append(
                    {"type": "section", "text": {"type": "mrkdwn", "text": question}}
                )
                elements = []
                for idx, text in enumerate(button_texts, start=1):
                    elements.append(
                        {
                            "type": "button",
                            "text": {"type": "plain_text", "text": text, "emoji": True},
                            "value": text,
                            "action_id": f"response_{idx}",
                        }
                    )
                blocks.append({"type": "actions", "elements": elements})

            # Resolve channel ID if destination is a channel name like #channel-name
            channel_to_use = destination
            if destination.startswith("#"):
                channel_name = destination[1:]
                channel_id = None
                cursor = None
                while True:
                    params_list = {
                        "limit": 1000,
                        "exclude_archived": "true",
                        "types": "public_channel,private_channel",
                    }
                    if cursor:
                        params_list["cursor"] = cursor
                    resp_list = await self.http_request(
                        "https://slack.com/api/conversations.list",
                        headers=headers,
                        params=params_list,
                        timeout=timeout,
                    )
                    list_data = resp_list.json()
                    if not list_data.get("ok", False):
                        return {
                            "status": "error",
                            "error": list_data.get(
                                "error", "Slack conversations.list failed"
                            ),
                            "error_type": "SlackAPIError",
                        }
                    for ch in list_data.get("channels", []):
                        if ch.get("name") == channel_name:
                            channel_id = ch.get("id")
                            break
                    if channel_id:
                        break
                    cursor = list_data.get("response_metadata", {}).get("next_cursor")
                    if not cursor:
                        break
                if not channel_id:
                    return {
                        "status": "error",
                        "error": f"Channel not found: {destination}",
                        "error_type": "ValidationError",
                    }
                channel_to_use = channel_id

            # Construct payload
            payload: dict[str, Any] = {
                "channel": channel_to_use,
                "text": question,
            }
            if blocks:
                payload["blocks"] = blocks

            # Make API call
            response = await self.http_request(
                endpoint,
                method="POST",
                headers=headers,
                json_data=payload,
                timeout=timeout,
            )

            # Parse response and extract meaningful data
            data = response.json()
            if not data.get("ok", False):
                return {
                    "status": "error",
                    "error": data.get("error", "Slack API returned an error"),
                    "error_type": "SlackAPIError",
                }

            return {
                "status": "success",
                "channel": data.get("channel"),
                "timestamp": data.get("ts")
                or (data.get("message", {}) or {}).get("ts"),
                "message_text": question,
                "responses": button_texts or [],
                "full_data": data,
            }

        except httpx.HTTPStatusError as e:
            return {
                "status": "error",
                "error": f"HTTP error occurred: {e!s}",
                "error_type": "HTTPStatusError",
            }
        except httpx.RequestError as e:
            return {
                "status": "error",
                "error": f"Request error occurred: {e!s}",
                "error_type": "RequestError",
            }
        except httpx.TimeoutException as e:
            return {
                "status": "error",
                "error": f"Request timed out: {e!s}",
                "error_type": "TimeoutException",
            }

class GetResponseAction(IntegrationAction):
    """Get the response to a previously asked question"""

    async def execute(self, **kwargs) -> dict[str, Any]:
        """Get the response to a previously asked question

        Args:
            **kwargs: Must contain:
                - question_id (string): Question ID

        Returns:
            Result with status and data or error"""
        # Extract parameters
        question_id = kwargs.get("question_id")

        # Validate required parameters
        if not question_id:
            return {
                "status": "error",
                "error": "Missing required parameter: question_id",
                "error_type": "ValidationError",
            }

        # Retrieve credentials
        bot_token = self.credentials.get("bot_token")
        if not bot_token:
            return {
                "status": "error",
                "error": "Missing bot_token in credentials",
                "error_type": "ConfigurationError",
            }

        # Retrieve settings
        timeout = self.settings.get("timeout", 30)

        try:
            endpoint_base = (
                self.settings.get("base_url", "").rstrip("/")
                if isinstance(self.settings.get("base_url", ""), str)
                else ""
            ).rstrip("/")
            endpoint = f"{endpoint_base or 'https://api.integration.local'}/questions/{question_id}/response"

            headers = {
                "Authorization": f"Bearer {bot_token}",
                "Accept": "application/json",
            }
            params: dict[str, Any] = {}

            response = await self.http_request(
                endpoint,
                headers=headers,
                params=params,
                timeout=timeout,
            )
            data = response.json()

            payload = data.get("data") if isinstance(data, dict) else None
            resp_obj = (
                payload
                if isinstance(payload, dict)
                else (data if isinstance(data, dict) else {})
            )

            response_text = None
            if isinstance(resp_obj, dict):
                response_text = (
                    resp_obj.get("response")
                    or resp_obj.get("answer")
                    or resp_obj.get("message")
                )
            response_received = (
                bool(resp_obj.get("response_received"))
                if isinstance(resp_obj, dict) and "response_received" in resp_obj
                else (response_text is not None)
            )

            return {
                "status": "success",
                "question_id": question_id,
                "response_received": bool(response_received),
                "response": response_text,
                "full_data": data,
            }

        except httpx.HTTPStatusError as e:
            if e.response.status_code == 404:
                return {
                    "status": "success",
                    "not_found": True,
                    "question_id": question_id,
                }
            return {
                "status": "error",
                "error": f"HTTP error occurred: {e!s}",
                "error_type": "HTTPStatusError",
            }
        except httpx.RequestError as e:
            return {
                "status": "error",
                "error": f"Request error occurred: {e!s}",
                "error_type": "RequestError",
            }
        except httpx.TimeoutException as e:
            return {
                "status": "error",
                "error": f"Request timed out: {e!s}",
                "error_type": "TimeoutException",
            }

class OnPollAction(IntegrationAction):
    """Start SlackBot and make health checks to it"""

    async def execute(self, **kwargs) -> dict[str, Any]:
        """Start SlackBot and make health checks to it

        Args:
            **kwargs: Must contain:
                - start_time (integer): Parameter ignored in this app
                - end_time (integer): Parameter ignored in this app
                - container_id (string): Parameter ignored in this app
                - container_count (integer): Parameter ignored in this app
                - artifact_count (integer): Parameter ignored in this app

        Returns:
            Result with status and data or error"""
        # Extract parameters
        kwargs.get("start_time")
        kwargs.get("end_time")
        kwargs.get("container_id")
        kwargs.get("container_count")
        kwargs.get("artifact_count")

        # Retrieve credentials
        bot_token = self.credentials.get("bot_token")
        if not bot_token:
            return {
                "status": "error",
                "error": "Missing bot_token in credentials",
                "error_type": "ConfigurationError",
            }

        # Retrieve settings
        timeout = self.settings.get("timeout", 30)

        try:
            auth_endpoint = "https://slack.com/api/auth.test"
            socket_endpoint = "https://slack.com/api/apps.connections.open"

            headers = {
                "Authorization": f"Bearer {bot_token}",
                "Accept": "application/json",
            }

            # Health check: verify token and identity
            auth_resp = await self.http_request(
                auth_endpoint,
                headers=headers,
                timeout=timeout,
            )
            auth_data = auth_resp.json()
            if not auth_data.get("ok", False):
                return {
                    "status": "error",
                    "error": auth_data.get("error", "Slack auth.test failed"),
                    "error_type": "SlackAPIError",
                    "data": {
                        "healthy": False,
                        "endpoint": "auth.test",
                        "response": auth_data,
                    },
                }

            # Attempt to open a Socket Mode connection URL as a readiness check
            socket_resp = await self.http_request(
                socket_endpoint,
                method="POST",
                headers=headers,
                timeout=timeout,
            )
            socket_data = socket_resp.json()
            if not socket_data.get("ok", False):
                return {
                    "status": "error",
                    "error": socket_data.get(
                        "error", "Slack apps.connections.open failed"
                    ),
                    "error_type": "SlackAPIError",
                    "data": {
                        "healthy": False,
                        "endpoint": "apps.connections.open",
                        "response": socket_data,
                    },
                }

            return {
                "status": "success",
                "message": "Slack API is accessible and Socket Mode URL retrieved",
                "data": {
                    "healthy": True,
                    "auth": {
                        "user_id": auth_data.get("user_id"),
                        "user": auth_data.get("user"),
                        "team": auth_data.get("team"),
                        "team_id": auth_data.get("team_id"),
                        "url": auth_data.get("url"),
                        "bot_id": auth_data.get("bot_id"),
                    },
                    "socket_mode": {
                        "url": socket_data.get("url"),
                        "app_id": socket_data.get("app_id"),
                        "expires_in": socket_data.get("expires_in"),
                    },
                    "raw": {
                        "auth_test": auth_data,
                        "apps_connections_open": socket_data,
                    },
                },
            }

        except httpx.HTTPStatusError as e:
            return {
                "status": "error",
                "error": f"HTTP error occurred: {e!s}",
                "error_type": "HTTPStatusError",
            }
        except httpx.RequestError as e:
            return {
                "status": "error",
                "error": f"Request error occurred: {e!s}",
                "error_type": "RequestError",
            }
        except httpx.TimeoutException as e:
            return {
                "status": "error",
                "error": f"Request timed out: {e!s}",
                "error_type": "TimeoutException",
            }

class StopBotAction(IntegrationAction):
    """Stop SlackBot"""

    async def execute(self, **kwargs) -> dict[str, Any]:
        """Stop SlackBot

        Returns:
            Result with status and data or error"""

        # Retrieve credentials
        bot_token = self.credentials.get("bot_token")
        if not bot_token:
            return {
                "status": "error",
                "error": "Missing bot_token in credentials",
                "error_type": "ConfigurationError",
            }

        # Retrieve settings
        timeout = self.settings.get("timeout", 30)

        try:
            endpoint = "https://slack.com/api/auth.revoke"

            headers = {
                "Authorization": f"Bearer {bot_token}",
                "Content-Type": "application/x-www-form-urlencoded",
            }

            response = await self.http_request(
                endpoint,
                method="POST",
                headers=headers,
                data={},
                timeout=timeout,
            )

            data = response.json()
            if not isinstance(data, dict):
                return {
                    "status": "error",
                    "error": "Invalid response format from Slack API",
                    "error_type": "InvalidResponse",
                }

            if data.get("ok"):
                return {
                    "status": "success",
                    "revoked": data.get("revoked", True),
                    "full_data": data,
                }
            return {
                "status": "error",
                "error": data.get("error", "Unknown error from Slack API"),
                "error_type": "SlackAPIError",
                "full_data": data,
            }

        except httpx.HTTPStatusError as e:
            return {
                "status": "error",
                "error": f"HTTP error occurred: {e!s}",
                "error_type": "HTTPStatusError",
            }
        except httpx.RequestError as e:
            return {
                "status": "error",
                "error": f"Request error occurred: {e!s}",
                "error_type": "RequestError",
            }
        except httpx.TimeoutException as e:
            return {
                "status": "error",
                "error": f"Request timed out: {e!s}",
                "error_type": "TimeoutException",
            }

class GetHistoryAction(IntegrationAction):
    """Get conversation history from specific Slack channel"""

    async def execute(self, **kwargs) -> dict[str, Any]:
        """Get conversation history from specific Slack channel

        Args:
            **kwargs: Must contain:
                - channel_id (string): Unique ID of a Slack channel
                - message_ts (string): Message timestamp (e.g. 1234567890.123456)

        Returns:
            Result with status and data or error"""
        # Extract parameters
        channel_id = kwargs.get("channel_id")
        message_ts = kwargs.get("message_ts")

        # Validate required parameters
        if not channel_id:
            return {
                "status": "error",
                "error": "Missing required parameter: channel_id",
                "error_type": "ValidationError",
            }

        # Retrieve credentials
        bot_token = self.credentials.get("bot_token")
        if not bot_token:
            return {
                "status": "error",
                "error": "Missing bot_token in credentials",
                "error_type": "ConfigurationError",
            }

        # Retrieve settings
        timeout = self.settings.get("timeout", 30)

        try:
            base_url = "https://slack.com/api"
            headers = {
                "Authorization": f"Bearer {bot_token}",
                "Accept": "application/json",
            }

            if not message_ts:
                # Fetch channel conversation history
                endpoint_history = f"{base_url}/conversations.history"
                params_history = {"channel": channel_id}
                response_history = await self.http_request(
                    endpoint_history,
                    headers=headers,
                    params=params_history,
                    timeout=timeout,
                )
                history_data = response_history.json()

                if not history_data.get("ok", False):
                    slack_error = history_data.get(
                        "error", "Failed to fetch conversation history"
                    )
                    if slack_error == "channel_not_found":
                        return {
                            "status": "success",
                            "not_found": True,
                            "channel_id": channel_id,
                            "error_code": slack_error,
                        }
                    return {
                        "status": "error",
                        "error": slack_error,
                        "error_type": "SlackAPIError",
                        "full_data": history_data,
                    }

                messages = history_data.get("messages", [])
                timestamps = [m.get("ts") for m in messages if m.get("ts")]

                final_messages = []
                threads_raw = []

                endpoint_replies = f"{base_url}/conversations.replies"
                for ts in timestamps:
                    params_replies = {"channel": channel_id, "ts": ts}
                    response_replies = await self.http_request(
                        endpoint_replies,
                        headers=headers,
                        params=params_replies,
                        timeout=timeout,
                    )
                    replies_data = response_replies.json()

                    if not replies_data.get("ok", False):
                        slack_error = replies_data.get(
                            "error", "Failed to fetch thread history"
                        )
                        if slack_error in (
                            "channel_not_found",
                            "thread_not_found",
                        ):
                            return {
                                "status": "success",
                                "not_found": True,
                                "channel_id": channel_id,
                                "message_ts": ts,
                                "error_code": slack_error,
                            }
                        return {
                            "status": "error",
                            "error": slack_error,
                            "error_type": "SlackAPIError",
                            "full_data": replies_data,
                        }

                    threads_raw.append(replies_data)
                    final_messages.extend(replies_data.get("messages", []))

                return {
                    "status": "success",
                    "channel_id": channel_id,
                    "num_messages": len(final_messages),
                    "messages": final_messages,
                    "full_data": {"history": history_data, "threads": threads_raw},
                }
            # Fetch specific thread history using provided message_ts
            endpoint_replies = f"{base_url}/conversations.replies"
            params_replies = {"channel": channel_id, "ts": message_ts}
            response_replies = await self.http_request(
                endpoint_replies,
                headers=headers,
                params=params_replies,
                timeout=timeout,
            )
            replies_data = response_replies.json()

            if not replies_data.get("ok", False):
                slack_error = replies_data.get("error", "Thread not found")
                if slack_error in ("channel_not_found", "thread_not_found"):
                    return {
                        "status": "success",
                        "not_found": True,
                        "channel_id": channel_id,
                        "message_ts": message_ts,
                        "error_code": slack_error,
                    }
                return {
                    "status": "error",
                    "error": slack_error,
                    "error_type": "SlackAPIError",
                    "full_data": replies_data,
                }

            messages = replies_data.get("messages", [])

            return {
                "status": "success",
                "channel_id": channel_id,
                "message_ts": message_ts,
                "num_messages": len(messages),
                "messages": messages,
                "full_data": replies_data,
            }

        except httpx.HTTPStatusError as e:
            if e.response.status_code == 404:
                return {
                    "status": "success",
                    "not_found": True,
                    "channel_id": channel_id,
                    "message_ts": message_ts,
                }
            return {
                "status": "error",
                "error": f"HTTP error occurred: {e!s}",
                "error_type": "HTTPStatusError",
            }
        except httpx.RequestError as e:
            return {
                "status": "error",
                "error": f"Request error occurred: {e!s}",
                "error_type": "RequestError",
            }
        except httpx.TimeoutException as e:
            return {
                "status": "error",
                "error": f"Request timed out: {e!s}",
                "error_type": "TimeoutException",
            }
