/**
 * API type aliases — bridges auto-generated OpenAPI types to clean domain names.
 *
 * The raw types live in src/generated/api.ts (auto-generated by openapi-typescript).
 * This file maps them to UI-friendly names so the rest of the codebase doesn't
 * couple to the generated schema naming convention (e.g., TaskRunResponse → TaskRun).
 *
 * UI-only types (filters, query params, visualization) remain in their respective
 * domain files within src/types/.
 */

import type { components } from '../generated/api';

type Schemas = components['schemas'];

// =============================================================================
// Alert types
// =============================================================================
export type AlertSeverity = Schemas['AlertSeverity'];
export type AlertStatus = Schemas['Status'];
export type AnalysisStatus = Schemas['AnalysisStatus'];
export type Alert = Schemas['AlertResponse'];
export type AlertAnalysisResponse = Schemas['AlertAnalysisResponse'];
export type Disposition = Schemas['DispositionResponse'];

// OCSF schema types (replace legacy NAS SourceCategory/EntityType/IOCType/DeviceAction)
export type FindingInfo = Schemas['FindingInfo'];
export type EvidenceArtifact = Schemas['EvidenceArtifact'];
export type Observable = Schemas['Observable'];
export type OCSFDevice = Schemas['OCSFDevice'];
export type Actor = Schemas['Actor'];

// =============================================================================
// Workflow Generation types
// =============================================================================
export type WorkflowGenerationStage = Schemas['WorkflowGenerationStage'];
export type WorkflowGenerationStatus = Schemas['WorkflowGenerationStatus'];
export type WorkflowGenerationPhase = Schemas['WorkflowGenerationPhase'];
export type WorkflowGenerationProgress = Schemas['WorkflowGenerationProgress'];
export type WorkflowGeneration = Schemas['WorkflowGenerationResponse'];
export type ActiveWorkflowResponse = Schemas['ActiveWorkflowResponse'];

// =============================================================================
// Workflow types
// =============================================================================
export type WorkflowNode = Schemas['WorkflowNodeResponse'];
export type WorkflowEdge = Schemas['WorkflowEdgeResponse'];
export type Workflow = Schemas['WorkflowResponse'];
export type WorkflowNodeInstance = Schemas['WorkflowNodeInstanceResponse'];
export type WorkflowEdgeInstance = Schemas['WorkflowEdgeInstanceResponse'];
export type WorkflowRunGraph = Schemas['WorkflowRunGraph'];
export type WorkflowRunStatus = Schemas['WorkflowRunStatus'];
export type WorkflowRunResponse = Schemas['WorkflowRunResponse'];

// =============================================================================
// Integration types
// =============================================================================
export type IntegrationInstance = Schemas['IntegrationResponse'];
export type IntegrationHealth = Schemas['IntegrationHealth'];
export type ManagedResourceBlock = Schemas['ManagedResourceSummary'];
export type Schedule = Schemas['ScheduleResponse'];
export type Credential = Schemas['CredentialMetadata'];
export type ProvisionFreeResponse = Schemas['ProvisionFreeResponse'];
export type ProvisionFreeIntegrationResult = Schemas['ProvisionFreeIntegrationResult'];

// Managed resource run (returned by GET /managed/{key}/runs)
export type ManagedRun = {
  task_run_id: string;
  status: string;
  run_context?: Record<string, unknown> | null;
  started_at?: string | null;
  completed_at?: string | null;
  created_at: string;
};

// Managed schedule (returned by GET/PUT /managed/{key}/schedule)
export type ManagedSchedule = {
  schedule_id: string;
  schedule_type: string;
  schedule_value: string;
  enabled: boolean;
  timezone: string;
  next_run_at?: string | null;
  last_run_at?: string | null;
};

// =============================================================================
// Task & TaskRun types
// =============================================================================
export type Task = Schemas['TaskResponse'];
export type TaskRun = Schemas['TaskRunResponse'];
export type TaskBuildingRun = Schemas['TaskGenerationResponse'];
export type TaskBuildingRunStatus = Schemas['TaskGenerationStatus'];
export type LLMUsage = Schemas['LLMUsageResponse'];

// =============================================================================
// Knowledge types
// =============================================================================
export type KUResponse = Schemas['KUResponse'];
export type DocumentKUResponse = Schemas['DocumentKUResponse'];
export type TableKUResponse = Schemas['TableKUResponse'];
export type IndexKUResponse = Schemas['IndexKUResponse'];

// =============================================================================
// Artifact types
// =============================================================================
export type Artifact = Schemas['ArtifactResponse'];

// =============================================================================
// Audit types
// =============================================================================
export type ActivityAuditResponse = Schemas['ActivityAuditResponse'];
export type ActivityAuditCreate = Schemas['ActivityAuditCreate'];
export type AuditSource = Schemas['AuditSource'];

// =============================================================================
// Settings types
// =============================================================================
export type AnalysisGroup = Schemas['AnalysisGroupResponse'];
export type AnalysisGroupCreate = Schemas['AnalysisGroupCreate'];
export type AlertRoutingRule = Schemas['AlertRoutingRuleResponse'];
export type AlertRoutingRuleCreate = Schemas['AlertRoutingRuleCreate'];

// =============================================================================
// Skill types
// =============================================================================
export type Skill = Schemas['SkillResponse'];
export type SkillFileContent = Schemas['SkillFileContent'];
export type SkillTree = Schemas['SkillTreeResponse'];
export type ContentReview = Schemas['ContentReviewResponse'];
export type ContentReviewRejectRequest = Schemas['ContentReviewRejectRequest'];
export type SkillImportResponse = Schemas['SkillImportResponse'];
export type ContentGateResult = Schemas['ContentGateResult'];
export type SkillDeleteCheck = Schemas['SkillDeleteCheck'];
export type StagedDocumentEntry = Schemas['StagedDocumentEntry'];

// =============================================================================
// Task Feedback types
// =============================================================================
export type TaskFeedback = Schemas['TaskFeedbackResponse'];
export type TaskFeedbackCreate = Schemas['TaskFeedbackCreate'];
export type TaskFeedbackUpdate = Schemas['TaskFeedbackUpdate'];

// =============================================================================
// Control Event types
// =============================================================================
export type ControlEventRule = Schemas['ControlEventRuleResponse'];
export type ControlEventRuleCreate = Schemas['ControlEventRuleCreate'];
export type ControlEventRuleUpdate = Schemas['ControlEventRuleUpdate'];
export type ControlEvent = Schemas['ControlEventResponse'];
export type ControlEventCreate = Schemas['ControlEventCreate'];
export type ChannelInfo = Schemas['ChannelInfo'];

// =============================================================================
// Node Template types
// =============================================================================
export type NodeTemplate = Schemas['NodeTemplateResponse'];
