"""
Post-Task Completion Hooks.

Extensible system for automatic manipulation of task output after Cy script execution.
"""

from dataclasses import dataclass
from typing import Any

from analysi.config.logging import get_logger

logger = get_logger(__name__)


# Prompt template for generating ai_analysis_title
AI_ANALYSIS_TITLE_PROMPT = """You are summarizing the results of a security analysis task.

Task: {task_name}
Purpose: {task_description}

Alert Context:
{alert_context}

The task produced this analysis:
{ai_analysis}

Create a crisp title (10-20 words max) that captures what was learned.
Rules:
- State the verdict/finding clearly (e.g., "Clean", "Malicious", "Suspicious", "Inconclusive")
- Only include facts from the analysis - do not invent or embellish details
- Focus on the key finding, not the process

Title:"""


@dataclass
class TaskMetadata:
    """Metadata about the task that was executed."""

    name: str
    description: str | None
    directive: str | None
    cy_name: str | None


class TaskPostHooks:
    """
    Extensible post-task-completion hooks.

    Runs after Cy script execution to perform automatic enrichments,
    logging, and other post-processing on task output.
    """

    def __init__(
        self,
        llm_summarize_func: Any,
        execution_context: dict[str, Any],
    ):
        """
        Initialize post-hooks with dependencies.

        Args:
            llm_summarize_func: Async function for LLM summarization (llm_summarize from CyLLMFunctions)
            execution_context: Task execution context (includes session for artifact capture)
        """
        self.llm_summarize = llm_summarize_func
        self.execution_context = execution_context
        self.session = execution_context.get("session")  # For artifact capture

    async def run_all_hooks(
        self,
        task_output: Any,
        task_metadata: TaskMetadata,
        original_input: dict[str, Any] | None = None,
    ) -> Any:
        """
        Run all registered hooks on task output.

        Args:
            task_output: The output from Cy script execution
            task_metadata: Metadata about the executed task
            original_input: The original input (alert) passed to the task

        Returns:
            Modified task output after all hooks have run
        """
        output = task_output

        # Hook 1: Auto-generate ai_analysis_title
        output = await self._maybe_add_analysis_title(
            output, task_metadata, original_input
        )

        # Future hooks go here...

        return output

    async def _maybe_add_analysis_title(
        self,
        output: Any,
        task_metadata: TaskMetadata,
        original_input: dict[str, Any] | None,
    ) -> Any:
        """
        Add ai_analysis_title if ai_analysis exists in enrichments.

        Scans the output for enrichments containing ai_analysis field,
        and auto-generates a concise title for each one.

        Args:
            output: Task output (typically a dict with enrichments)
            task_metadata: Task metadata for context
            original_input: Original alert input for context

        Returns:
            Output with ai_analysis_title added where appropriate
        """
        if not isinstance(output, dict):
            return output

        enrichments = output.get("enrichments")
        if not isinstance(enrichments, dict):
            return output

        # Find the task's enrichment (using cy_name)
        cy_name = task_metadata.cy_name or self.execution_context.get("cy_name")
        if not cy_name:
            logger.debug("No cy_name available - skipping ai_analysis_title generation")
            return output

        task_enrichment = enrichments.get(cy_name)
        if not isinstance(task_enrichment, dict):
            return output

        ai_analysis = task_enrichment.get("ai_analysis")
        if not ai_analysis:
            return output

        # Don't overwrite existing title
        if "ai_analysis_title" in task_enrichment:
            logger.debug("ai_analysis_title already exists - skipping generation")
            return output

        try:
            # Build context from alert
            alert_context = self._build_alert_context(original_input)

            # Generate title using llm_summarize with directive as system prompt
            title = await self._generate_title(
                ai_analysis=ai_analysis,
                task_metadata=task_metadata,
                alert_context=alert_context,
            )

            # Add title to enrichment
            task_enrichment["ai_analysis_title"] = title
            logger.info(
                "autogenerated_aianalysistitle_for", cy_name=cy_name, title=title
            )

        except Exception as e:
            # Don't fail the task if title generation fails
            logger.warning("failed_to_generate_aianalysistitle", error=str(e))

        return output

    def _build_alert_context(self, original_input: dict[str, Any] | None) -> str:
        """Build a brief context string from the alert."""
        if not original_input or not isinstance(original_input, dict):
            return "No alert context available"

        parts = []
        if title := original_input.get("title"):
            parts.append(f"Title: {title}")
        if severity := original_input.get("severity"):
            parts.append(f"Severity: {severity}")
        if rule_name := original_input.get("rule_name"):
            parts.append(f"Rule: {rule_name}")

        return " | ".join(parts) if parts else "No alert context available"

    async def _generate_title(
        self,
        ai_analysis: Any,
        task_metadata: TaskMetadata,
        alert_context: str,
    ) -> str:
        """Generate a crisp title for the ai_analysis."""
        import json
        import time

        # Convert ai_analysis to string if needed
        if isinstance(ai_analysis, dict):
            analysis_text = json.dumps(ai_analysis, indent=2)
        else:
            analysis_text = str(ai_analysis)

        # Truncate if too long (keep first 2000 chars)
        if len(analysis_text) > 2000:
            analysis_text = analysis_text[:2000] + "..."

        # Build context for summarization
        context = AI_ANALYSIS_TITLE_PROMPT.format(
            task_name=task_metadata.name,
            task_description=task_metadata.description or "Security analysis task",
            alert_context=alert_context,
            ai_analysis=analysis_text,
        )

        # Track timing for artifact capture
        start_time = time.time()

        # Use task's directive as system prompt if available
        title = await self.llm_summarize(
            text=analysis_text,
            context=context,
            directive=task_metadata.directive,
            max_words=20,
        )

        duration_ms = int((time.time() - start_time) * 1000)

        # Capture artifact (fire-and-forget)
        await self._capture_summarization_artifact(
            prompt=context,
            completion=title,
            duration_ms=duration_ms,
        )

        # Clean up the title
        title = title.strip().strip("\"'")

        # Truncate if somehow still too long
        words = title.split()
        if len(words) > 25:
            title = " ".join(words[:20]) + "..."

        return title

    async def _capture_summarization_artifact(
        self,
        prompt: str,
        completion: str,
        duration_ms: int,
    ) -> None:
        """
        Capture AI Task Summarizer as llm_summarization artifact.

        Fire-and-forget - failures are logged but don't break the hook.
        """
        if not self.session:
            logger.debug("No session - skipping artifact capture")
            return

        try:
            import json
            from datetime import UTC, datetime
            from uuid import UUID

            from analysi.schemas.artifact import ArtifactCreate
            from analysi.services.artifact_service import ArtifactService

            tenant_id = self.execution_context.get("tenant_id")
            if not tenant_id:
                logger.debug("No tenant_id - skipping artifact capture")
                return

            # Safe UUID conversion (IDs are strings in execution_context)
            def safe_uuid(val: str | None) -> UUID | None:
                if not val:
                    return None
                try:
                    return UUID(val) if isinstance(val, str) else val
                except (ValueError, TypeError):
                    return None

            content = {
                "prompt": prompt,
                "completion": completion,
                "duration_ms": duration_ms,
                "timestamp": datetime.now(UTC).isoformat(),
            }

            artifact_data = ArtifactCreate(
                name="AI Task Summarizer",
                content=json.dumps(content),
                artifact_type="llm_summarization",
                task_run_id=safe_uuid(self.execution_context.get("task_run_id")),
                workflow_run_id=safe_uuid(
                    self.execution_context.get("workflow_run_id")
                ),
                workflow_node_instance_id=safe_uuid(
                    self.execution_context.get("workflow_node_instance_id")
                ),
                analysis_id=safe_uuid(self.execution_context.get("analysis_id")),
                source="auto_capture",
            )

            artifact_svc = ArtifactService(self.session)
            await artifact_svc.create_artifact(tenant_id, artifact_data)
            logger.debug("Captured AI Task Summarizer artifact")

        except Exception as e:
            logger.warning("failed_to_capture_summarization_artifact", error=str(e))


def create_task_post_hooks(
    llm_functions: dict[str, Any],
    execution_context: dict[str, Any],
) -> TaskPostHooks | None:
    """
    Create TaskPostHooks instance if LLM functions are available.

    Args:
        llm_functions: Dictionary of LLM functions (must contain llm_summarize)
        execution_context: Task execution context

    Returns:
        TaskPostHooks instance or None if llm_summarize not available
    """
    llm_summarize = llm_functions.get("llm_summarize")
    if not llm_summarize:
        logger.debug("llm_summarize not available - post-hooks disabled")
        return None

    return TaskPostHooks(
        llm_summarize_func=llm_summarize,
        execution_context=execution_context,
    )
