"""Integration tests for Task API cy_name functionality."""

import uuid
from collections.abc import AsyncGenerator

import pytest
from httpx import ASGITransport, AsyncClient

from analysi.db.session import get_db
from analysi.main import app
from analysi.models.auth import SYSTEM_USER_ID
from analysi.repositories.task import TaskRepository


@pytest.mark.asyncio
@pytest.mark.integration
class TestTaskCyNameEndpoints:
    """Test Task API endpoints with cy_name functionality."""

    @pytest.fixture
    async def client(self, integration_test_session) -> AsyncGenerator[AsyncClient]:
        """Create an async HTTP client for testing with test database."""

        # Override the database dependency to use test database
        async def override_get_db():
            yield integration_test_session

        app.dependency_overrides[get_db] = override_get_db

        transport = ASGITransport(app=app)
        async with AsyncClient(transport=transport, base_url="http://test") as client:
            yield client

        # Clean up the override
        app.dependency_overrides.clear()

    @pytest.fixture
    def tenant_id(self):
        """Create unique tenant ID for each test."""
        return f"test-tenant-{uuid.uuid4().hex[:8]}"

    @pytest.fixture
    async def repository(self, integration_test_session):
        """Create TaskRepository with test session."""
        return TaskRepository(integration_test_session)

    @pytest.mark.asyncio
    async def test_list_tasks_with_cy_name_filter(
        self, client: AsyncClient, tenant_id: str, repository
    ):
        """Test filtering tasks by cy_name query parameter."""
        # Create tasks with different cy_names
        tasks_data = [
            {
                "tenant_id": tenant_id,
                "name": "Incident Response",
                "cy_name": "incident_response",
                "script": "TASK ir: RETURN 'incident'",
                "created_by": str(SYSTEM_USER_ID),
            },
            {
                "tenant_id": tenant_id,
                "name": "Data Analysis",
                "cy_name": "data_analysis",
                "script": "TASK da: RETURN 'analysis'",
                "created_by": str(SYSTEM_USER_ID),
            },
            {
                "tenant_id": tenant_id,
                "name": "Security Scan",
                "cy_name": "security_scan",
                "script": "TASK ss: RETURN 'scan'",
                "created_by": str(SYSTEM_USER_ID),
            },
        ]

        # Create tasks directly in database
        for task_data in tasks_data:
            await repository.create(task_data)

        # Query with cy_name filter
        response = await client.get(f"/v1/{tenant_id}/tasks?cy_name=incident_response")

        assert response.status_code == 200
        result = response.json()
        assert result["meta"]["total"] == 1
        assert len(result["data"]) == 1
        # Note: cy_name is not in the response schema yet
        assert result["data"][0]["name"] == "Incident Response"

    @pytest.mark.asyncio
    async def test_create_task_with_cy_name(self, client: AsyncClient, tenant_id: str):
        """Test creating task with explicit cy_name."""
        task_data = {
            "name": "Custom Task",
            "cy_name": "custom_task_name",
            "script": "TASK custom: RETURN 'test'",
            "created_by": str(SYSTEM_USER_ID),
        }

        response = await client.post(f"/v1/{tenant_id}/tasks", json=task_data)

        # Should succeed - cy_name field is accepted but not returned in response yet
        assert response.status_code == 201
        result = response.json()["data"]
        assert result["name"] == "Custom Task"

    @pytest.mark.asyncio
    async def test_create_task_auto_generate_cy_name(
        self, client: AsyncClient, tenant_id: str, repository
    ):
        """Test that task creation auto-generates cy_name when not provided."""
        task_data = {
            "name": "My Complex Task Name",
            "script": "TASK complex: RETURN 'auto'",
            "created_by": str(SYSTEM_USER_ID),
        }

        response = await client.post(f"/v1/{tenant_id}/tasks", json=task_data)

        assert response.status_code == 201
        task_id = response.json()["data"]["id"]

        # Verify cy_name was auto-generated by checking database directly
        task = await repository.get_by_id(uuid.UUID(task_id), tenant_id)
        assert task.component.cy_name == "my_complex_task_name"

    @pytest.mark.asyncio
    async def test_create_task_cy_name_validation(
        self, client: AsyncClient, tenant_id: str
    ):
        """Test cy_name validation rules."""
        # Test various invalid cy_names that should be rejected
        invalid_cases = [
            "123invalid",  # Starts with number
            "has-dashes",  # Contains dashes
            "has spaces",  # Contains spaces
            "CamelCase",  # Not lowercase
        ]

        for invalid_cy_name in invalid_cases:
            task_data = {
                "name": f"Task {invalid_cy_name}",
                "cy_name": invalid_cy_name,
                "script": "TASK test: RETURN 'valid'",
                "created_by": str(SYSTEM_USER_ID),
            }

            response = await client.post(f"/v1/{tenant_id}/tasks", json=task_data)

            # Schema validates cy_name pattern - should reject invalid ones
            assert response.status_code == 422
            errors = response.json().get("errors", [])
            assert any("cy_name" in str(err) for err in errors)

    @pytest.mark.asyncio
    async def test_list_tasks_without_cy_name_filter(
        self, client: AsyncClient, tenant_id: str, repository
    ):
        """Test that listing tasks without cy_name filter returns all tasks."""
        # Create multiple tasks
        for i in range(3):
            task_data = {
                "tenant_id": tenant_id,
                "name": f"Task {i}",
                "cy_name": f"task_{i}",
                "script": f"TASK t{i}: RETURN '{i}'",
                "created_by": str(SYSTEM_USER_ID),
            }
            await repository.create(task_data)

        # List without filter
        response = await client.get(f"/v1/{tenant_id}/tasks")

        assert response.status_code == 200
        result = response.json()
        assert result["meta"]["total"] == 3
        assert len(result["data"]) == 3

    @pytest.mark.asyncio
    async def test_cy_name_in_different_tenants(self, client: AsyncClient):
        """Test that same cy_name can exist in different tenants."""
        tenant1 = f"tenant-{uuid.uuid4().hex[:8]}"
        tenant2 = f"tenant-{uuid.uuid4().hex[:8]}"

        task_data = {
            "name": "Shared Task",
            "cy_name": "shared_task",
            "script": "TASK shared: RETURN 'shared'",
            "created_by": str(SYSTEM_USER_ID),
        }

        # Create in tenant1
        response1 = await client.post(f"/v1/{tenant1}/tasks", json=task_data)
        assert response1.status_code == 201

        # Create in tenant2 - should succeed
        response2 = await client.post(f"/v1/{tenant2}/tasks", json=task_data)
        assert response2.status_code == 201

        # Verify each tenant only sees their own task
        list1 = await client.get(f"/v1/{tenant1}/tasks")
        list2 = await client.get(f"/v1/{tenant2}/tasks")

        assert list1.json()["meta"]["total"] == 1
        assert list2.json()["meta"]["total"] == 1
